
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.falloutwastelands.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.falloutwastelands.block.WornMetalStairsBlock;
import net.mcreator.falloutwastelands.block.WornMetalSlabBlock;
import net.mcreator.falloutwastelands.block.WornMetalPillarBlock;
import net.mcreator.falloutwastelands.block.WornMetalBlock;
import net.mcreator.falloutwastelands.block.WoodedconcreteBlock;
import net.mcreator.falloutwastelands.block.WirefenceBlock;
import net.mcreator.falloutwastelands.block.WastelandventconcreteBlock;
import net.mcreator.falloutwastelands.block.WastelandtilesstairsBlock;
import net.mcreator.falloutwastelands.block.WastelandtilesslabBlock;
import net.mcreator.falloutwastelands.block.WastelandtilesBlock;
import net.mcreator.falloutwastelands.block.WastelandshortburntgrassBlock;
import net.mcreator.falloutwastelands.block.WastelandsPortalBlock;
import net.mcreator.falloutwastelands.block.WastelandredstoneoreBlock;
import net.mcreator.falloutwastelands.block.WastelandpebbleBlock;
import net.mcreator.falloutwastelands.block.WastelandlapisoreBlock;
import net.mcreator.falloutwastelands.block.WastelandironoreBlock;
import net.mcreator.falloutwastelands.block.WastelandhardstoneBlock;
import net.mcreator.falloutwastelands.block.WastelandgravelBlock;
import net.mcreator.falloutwastelands.block.WastelandgrassbushBlock;
import net.mcreator.falloutwastelands.block.WastelandgrassblockBlock;
import net.mcreator.falloutwastelands.block.WastelandemeraldoreBlock;
import net.mcreator.falloutwastelands.block.WastelanddrydirtBlock;
import net.mcreator.falloutwastelands.block.WastelanddiamondoreBlock;
import net.mcreator.falloutwastelands.block.WastelandcopperoreBlock;
import net.mcreator.falloutwastelands.block.WastelandcoaloreBlock;
import net.mcreator.falloutwastelands.block.WastelandburntgrassBlock;
import net.mcreator.falloutwastelands.block.WastelandbricksBlock;
import net.mcreator.falloutwastelands.block.WastelandStoneBlock;
import net.mcreator.falloutwastelands.block.WastelandRoadSlabBlock;
import net.mcreator.falloutwastelands.block.WastelandRoadBlockBlock;
import net.mcreator.falloutwastelands.block.WastelandGoldoreBlock;
import net.mcreator.falloutwastelands.block.WastelandDirtBlock;
import net.mcreator.falloutwastelands.block.WastelandCrackedBrickBlock;
import net.mcreator.falloutwastelands.block.WastelandConcreteWallBlock;
import net.mcreator.falloutwastelands.block.WastelandConcreteStairsBlock;
import net.mcreator.falloutwastelands.block.WastelandConcreteSlabBlock;
import net.mcreator.falloutwastelands.block.WastelandConcreteBlock;
import net.mcreator.falloutwastelands.block.WastelandCobblestoneBlock;
import net.mcreator.falloutwastelands.block.WastelandBrokenGlassBlock;
import net.mcreator.falloutwastelands.block.WastelandBrickslabBlock;
import net.mcreator.falloutwastelands.block.WastelandBricksStairsBlock;
import net.mcreator.falloutwastelands.block.WastelandBricksSlabBlock;
import net.mcreator.falloutwastelands.block.WastelandBrickWallBlock;
import net.mcreator.falloutwastelands.block.WastelandBrickStairsBlock;
import net.mcreator.falloutwastelands.block.WastelandBrickBlock;
import net.mcreator.falloutwastelands.block.WastelandAluminumOreBlock;
import net.mcreator.falloutwastelands.block.WasteSandBlock;
import net.mcreator.falloutwastelands.block.WallWastelandCobblestoneBlock;
import net.mcreator.falloutwastelands.block.VaultWallExposedBlock;
import net.mcreator.falloutwastelands.block.VaultWallCurvedBlock;
import net.mcreator.falloutwastelands.block.VaultWallBlock;
import net.mcreator.falloutwastelands.block.VaultVentBlock;
import net.mcreator.falloutwastelands.block.VaultReinforcedPillarBlock;
import net.mcreator.falloutwastelands.block.VaultPillarBlock;
import net.mcreator.falloutwastelands.block.VaultFloorBlock;
import net.mcreator.falloutwastelands.block.UtsolBlock;
import net.mcreator.falloutwastelands.block.UraniumOreBlock;
import net.mcreator.falloutwastelands.block.UraniumBlockBlock;
import net.mcreator.falloutwastelands.block.TrashBinBlock;
import net.mcreator.falloutwastelands.block.TireStackBlock;
import net.mcreator.falloutwastelands.block.TinOreBlock;
import net.mcreator.falloutwastelands.block.TinBlockBlock;
import net.mcreator.falloutwastelands.block.TheGlowDirtBlock;
import net.mcreator.falloutwastelands.block.TerminalBlock;
import net.mcreator.falloutwastelands.block.TelevisionBlock;
import net.mcreator.falloutwastelands.block.SupermutantgoreBlock;
import net.mcreator.falloutwastelands.block.SubwaybricksBlock;
import net.mcreator.falloutwastelands.block.StrippedmolderwoodlogBlock;
import net.mcreator.falloutwastelands.block.SteelPoleBlock;
import net.mcreator.falloutwastelands.block.SteelBlockBlock;
import net.mcreator.falloutwastelands.block.SteelBarsBlock;
import net.mcreator.falloutwastelands.block.StairWastelandCobblestoneBlock;
import net.mcreator.falloutwastelands.block.SlabWastelandCobblestoneBlock;
import net.mcreator.falloutwastelands.block.SingleScaffoldBlockBlock;
import net.mcreator.falloutwastelands.block.SheetmetalstairsBlock;
import net.mcreator.falloutwastelands.block.SheetmetalblockBlock;
import net.mcreator.falloutwastelands.block.ScaffoldingWalkwayslabBlock;
import net.mcreator.falloutwastelands.block.ScaffoldingWalkwaysBlockBlock;
import net.mcreator.falloutwastelands.block.ScaffoldingWalkwayStairsBlock;
import net.mcreator.falloutwastelands.block.RustysheetmetalstairsBlock;
import net.mcreator.falloutwastelands.block.RustySheetmetalblockBlock;
import net.mcreator.falloutwastelands.block.RustedSheetMetalWallBlock;
import net.mcreator.falloutwastelands.block.RustBlockBlock;
import net.mcreator.falloutwastelands.block.RuinsGroundBlock;
import net.mcreator.falloutwastelands.block.RuinsBlock;
import net.mcreator.falloutwastelands.block.RuinsBaseBlock;
import net.mcreator.falloutwastelands.block.RoofMetalBlock;
import net.mcreator.falloutwastelands.block.RockydirtBlock;
import net.mcreator.falloutwastelands.block.ReinforcedPlanksBlock;
import net.mcreator.falloutwastelands.block.RadiationBarrelBlock;
import net.mcreator.falloutwastelands.block.PlasterBlock;
import net.mcreator.falloutwastelands.block.PipeBlock;
import net.mcreator.falloutwastelands.block.OxidizedMetalWallBlock;
import net.mcreator.falloutwastelands.block.OxidizedMetalStairBlock;
import net.mcreator.falloutwastelands.block.OxidizedMetalSlabBlock;
import net.mcreator.falloutwastelands.block.OxidizedMetalBlock;
import net.mcreator.falloutwastelands.block.MoltenTinBlock;
import net.mcreator.falloutwastelands.block.MoltenSteelBlock;
import net.mcreator.falloutwastelands.block.MoltenCopperBlock;
import net.mcreator.falloutwastelands.block.MoltenBoxiteBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodWoodBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodStairsBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodSlabBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodPressurePlateBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodPlanksBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodLogBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodFenceGateBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodFenceBlock;
import net.mcreator.falloutwastelands.block.Molder_WoodButtonBlock;
import net.mcreator.falloutwastelands.block.MolderWoodTrapdoorBlock;
import net.mcreator.falloutwastelands.block.MolderWoodDoorBlock;
import net.mcreator.falloutwastelands.block.MixerBlock;
import net.mcreator.falloutwastelands.block.MilitaryPlatingWalkwayBlock;
import net.mcreator.falloutwastelands.block.MilitaryPlatingSlabBlock;
import net.mcreator.falloutwastelands.block.MilitaryMetalwindowBlock;
import net.mcreator.falloutwastelands.block.MilitaryMetalStairBlock;
import net.mcreator.falloutwastelands.block.MilitaryMetalRadiationBlock;
import net.mcreator.falloutwastelands.block.MilitaryMetalPlateWallBlock;
import net.mcreator.falloutwastelands.block.MilitaryMetalPlateBlock;
import net.mcreator.falloutwastelands.block.MilitaryMetalHazardBlock;
import net.mcreator.falloutwastelands.block.MilitaryMetalDoorBlock;
import net.mcreator.falloutwastelands.block.MetalShelfBlock;
import net.mcreator.falloutwastelands.block.MetalChairBlock;
import net.mcreator.falloutwastelands.block.MetalBarrelBlock;
import net.mcreator.falloutwastelands.block.MeltedSteelBlockBlock;
import net.mcreator.falloutwastelands.block.MeltedIronBlockBlock;
import net.mcreator.falloutwastelands.block.MedicalBoxBlock;
import net.mcreator.falloutwastelands.block.LockerBlock;
import net.mcreator.falloutwastelands.block.LinedconcreteBlock;
import net.mcreator.falloutwastelands.block.LightTubeBlock;
import net.mcreator.falloutwastelands.block.LeadOreBlock;
import net.mcreator.falloutwastelands.block.LeadBlockBlock;
import net.mcreator.falloutwastelands.block.LandmineBlock;
import net.mcreator.falloutwastelands.block.IndustrialWalkwaystairsBlock;
import net.mcreator.falloutwastelands.block.IndustrialWalkwayslabBlock;
import net.mcreator.falloutwastelands.block.IndustrialWalkwayBlock;
import net.mcreator.falloutwastelands.block.IndustrialSupportBlock;
import net.mcreator.falloutwastelands.block.IndustrialPlatingBlock;
import net.mcreator.falloutwastelands.block.IndustrialDoorBlock;
import net.mcreator.falloutwastelands.block.IndustrialAlloyWarningBlock;
import net.mcreator.falloutwastelands.block.IndustrialAlloyStairBlock;
import net.mcreator.falloutwastelands.block.IndustrialAlloySlabBlock;
import net.mcreator.falloutwastelands.block.IndustrialAlloyPlainBlock;
import net.mcreator.falloutwastelands.block.IndustrialAlloyBottomRivetBlock;
import net.mcreator.falloutwastelands.block.IndustrialAlloyBlock;
import net.mcreator.falloutwastelands.block.IndustrialAllowMidRivetBlock;
import net.mcreator.falloutwastelands.block.HorizontallinedconcreteBlock;
import net.mcreator.falloutwastelands.block.HardconcretestairsBlock;
import net.mcreator.falloutwastelands.block.HardconcreteBlock;
import net.mcreator.falloutwastelands.block.HangardoorBlock;
import net.mcreator.falloutwastelands.block.GreyTilesBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialWalkwayStairsBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialWalkwaySlabBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialWalkwayBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialAlloyplateBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialAlloybottomrivetBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialAlloyStairBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialAlloySlabBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialAlloyBlock;
import net.mcreator.falloutwastelands.block.GreyIndustrialAllowmidrivetBlock;
import net.mcreator.falloutwastelands.block.GoreBlock;
import net.mcreator.falloutwastelands.block.FridgeBlock;
import net.mcreator.falloutwastelands.block.FloorPapersBlock;
import net.mcreator.falloutwastelands.block.FilingCabinetBlock;
import net.mcreator.falloutwastelands.block.ExposedRustBlockBlock;
import net.mcreator.falloutwastelands.block.EnclaveDoorBlock;
import net.mcreator.falloutwastelands.block.EnclaveBunkerStairsBlock;
import net.mcreator.falloutwastelands.block.EnclaveBunkerFloorBlock;
import net.mcreator.falloutwastelands.block.EnclaveBunkerBlockLogoBlock;
import net.mcreator.falloutwastelands.block.EnclaveBunkerBlockBlock;
import net.mcreator.falloutwastelands.block.DoubleScaffoldWallBlock;
import net.mcreator.falloutwastelands.block.DoubleScaffoldBlockBlock;
import net.mcreator.falloutwastelands.block.CrackedWastelandConcreteWallBlock;
import net.mcreator.falloutwastelands.block.CrackedWastelandConcreteStairsBlock;
import net.mcreator.falloutwastelands.block.CrackedWastelandConcreteSlabsBlock;
import net.mcreator.falloutwastelands.block.CrackedWastelandConcreteBlock;
import net.mcreator.falloutwastelands.block.ConcreteTileBlock;
import net.mcreator.falloutwastelands.block.CharredMolderWoodPlankBlock;
import net.mcreator.falloutwastelands.block.CharredMolderStairsBlock;
import net.mcreator.falloutwastelands.block.CharredMolderSlabBlock;
import net.mcreator.falloutwastelands.block.CharredMolderFenceBlock;
import net.mcreator.falloutwastelands.block.CentralunitBlock;
import net.mcreator.falloutwastelands.block.CeilingLightBlock;
import net.mcreator.falloutwastelands.block.CageBlock;
import net.mcreator.falloutwastelands.block.BurnishedGlassPaneBlock;
import net.mcreator.falloutwastelands.block.BurnishedGlassBlock;
import net.mcreator.falloutwastelands.block.BunkerBlockLightBlock;
import net.mcreator.falloutwastelands.block.BosSteelStairBlock;
import net.mcreator.falloutwastelands.block.BosSteelSlabsBlock;
import net.mcreator.falloutwastelands.block.BosSteelBlockBlock;
import net.mcreator.falloutwastelands.block.BosMetalStairsBlock;
import net.mcreator.falloutwastelands.block.BosMetalPlatingLightedBlock;
import net.mcreator.falloutwastelands.block.BosMetalPlatingBlock;
import net.mcreator.falloutwastelands.block.BosDoorBlock;
import net.mcreator.falloutwastelands.block.BlastedGlassPaneBlock;
import net.mcreator.falloutwastelands.block.BlastedGlassBlock;
import net.mcreator.falloutwastelands.block.BlackTilesBlock;
import net.mcreator.falloutwastelands.block.BarricadesheetmetalblockBlock;
import net.mcreator.falloutwastelands.block.BarricadeplanksBlock;
import net.mcreator.falloutwastelands.block.BarbedWiresBlock;
import net.mcreator.falloutwastelands.block.BASEcoreBlock;
import net.mcreator.falloutwastelands.block.AmmoBoxBlock;
import net.mcreator.falloutwastelands.block.AluminumBlockBlock;
import net.mcreator.falloutwastelands.FalloutWastelandsMod;

public class FalloutWastelandsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FalloutWastelandsMod.MODID);
	public static final RegistryObject<Block> WASTELAND_DIRT = REGISTRY.register("wasteland_dirt", () -> new WastelandDirtBlock());
	public static final RegistryObject<Block> WASTELAND_STONE = REGISTRY.register("wasteland_stone", () -> new WastelandStoneBlock());
	public static final RegistryObject<Block> WASTELANDS_PORTAL = REGISTRY.register("wastelands_portal", () -> new WastelandsPortalBlock());
	public static final RegistryObject<Block> WASTELANDGRASSBLOCK = REGISTRY.register("wastelandgrassblock", () -> new WastelandgrassblockBlock());
	public static final RegistryObject<Block> CRACKED_WASTELAND_CONCRETE_WALL = REGISTRY.register("cracked_wasteland_concrete_wall", () -> new CrackedWastelandConcreteWallBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_BUTTON = REGISTRY.register("molder_wood_button", () -> new Molder_WoodButtonBlock());
	public static final RegistryObject<Block> WASTELAND_CONCRETE_STAIRS = REGISTRY.register("wasteland_concrete_stairs", () -> new WastelandConcreteStairsBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_PRESSURE_PLATE = REGISTRY.register("molder_wood_pressure_plate", () -> new Molder_WoodPressurePlateBlock());
	public static final RegistryObject<Block> WASTELAND_ROOTY_DIRT = REGISTRY.register("wasteland_rooty_dirt", () -> new UtsolBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_LOG = REGISTRY.register("molder_wood_log", () -> new Molder_WoodLogBlock());
	public static final RegistryObject<Block> CRACKED_WASTELAND_CONCRETE = REGISTRY.register("cracked_wasteland_concrete", () -> new CrackedWastelandConcreteBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_DOOR = REGISTRY.register("molder_wood_door", () -> new MolderWoodDoorBlock());
	public static final RegistryObject<Block> THE_GLOW_DIRT = REGISTRY.register("the_glow_dirt", () -> new TheGlowDirtBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_TRAPDOOR = REGISTRY.register("molder_wood_trapdoor", () -> new MolderWoodTrapdoorBlock());
	public static final RegistryObject<Block> SLAB_WASTELAND_COBBLESTONE = REGISTRY.register("slab_wasteland_cobblestone", () -> new SlabWastelandCobblestoneBlock());
	public static final RegistryObject<Block> WASTELAND_COBBLESTONE = REGISTRY.register("wasteland_cobblestone", () -> new WastelandCobblestoneBlock());
	public static final RegistryObject<Block> STAIR_WASTELAND_COBBLESTONE = REGISTRY.register("stair_wasteland_cobblestone", () -> new StairWastelandCobblestoneBlock());
	public static final RegistryObject<Block> WASTELAND_CONCRETE = REGISTRY.register("wasteland_concrete", () -> new WastelandConcreteBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_STAIRS = REGISTRY.register("molder_wood_stairs", () -> new Molder_WoodStairsBlock());
	public static final RegistryObject<Block> CRACKED_WASTELAND_CONCRETE_STAIRS = REGISTRY.register("cracked_wasteland_concrete_stairs", () -> new CrackedWastelandConcreteStairsBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_PLANKS = REGISTRY.register("molder_wood_planks", () -> new Molder_WoodPlanksBlock());
	public static final RegistryObject<Block> WASTELAND_BRICK = REGISTRY.register("wasteland_brick", () -> new WastelandBrickBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_FENCE = REGISTRY.register("molder_wood_fence", () -> new Molder_WoodFenceBlock());
	public static final RegistryObject<Block> WASTELAND_CONCRETE_WALL = REGISTRY.register("wasteland_concrete_wall", () -> new WastelandConcreteWallBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_WOOD = REGISTRY.register("molder_wood_wood", () -> new Molder_WoodWoodBlock());
	public static final RegistryObject<Block> CRACKED_WASTELAND_CONCRETE_SLABS = REGISTRY.register("cracked_wasteland_concrete_slabs", () -> new CrackedWastelandConcreteSlabsBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_SLAB = REGISTRY.register("molder_wood_slab", () -> new Molder_WoodSlabBlock());
	public static final RegistryObject<Block> WALL_WASTELAND_COBBLESTONE = REGISTRY.register("wall_wasteland_cobblestone", () -> new WallWastelandCobblestoneBlock());
	public static final RegistryObject<Block> MOLDER_WOOD_FENCE_GATE = REGISTRY.register("molder_wood_fence_gate", () -> new Molder_WoodFenceGateBlock());
	public static final RegistryObject<Block> WASTELAND_CONCRETE_SLAB = REGISTRY.register("wasteland_concrete_slab", () -> new WastelandConcreteSlabBlock());
	public static final RegistryObject<Block> WASTELANDGRASSBUSH = REGISTRY.register("wastelandgrassbush", () -> new WastelandgrassbushBlock());
	public static final RegistryObject<Block> WASTELANDBURNTGRASS = REGISTRY.register("wastelandburntgrass", () -> new WastelandburntgrassBlock());
	public static final RegistryObject<Block> WASTELANDSHORTBURNTGRASS = REGISTRY.register("wastelandshortburntgrass", () -> new WastelandshortburntgrassBlock());
	public static final RegistryObject<Block> WASTELAND_BRICK_STAIRS = REGISTRY.register("wasteland_brick_stairs", () -> new WastelandBrickStairsBlock());
	public static final RegistryObject<Block> WASTELAND_BRICKSLAB = REGISTRY.register("wasteland_brickslab", () -> new WastelandBrickslabBlock());
	public static final RegistryObject<Block> WASTELANDPEBBLE = REGISTRY.register("wastelandpebble", () -> new WastelandpebbleBlock());
	public static final RegistryObject<Block> WASTELANDGRAVEL = REGISTRY.register("wastelandgravel", () -> new WastelandgravelBlock());
	public static final RegistryObject<Block> WASTELANDCOALORE = REGISTRY.register("wastelandcoalore", () -> new WastelandcoaloreBlock());
	public static final RegistryObject<Block> WASTELANDCOPPERORE = REGISTRY.register("wastelandcopperore", () -> new WastelandcopperoreBlock());
	public static final RegistryObject<Block> WASTELAND_GOLDORE = REGISTRY.register("wasteland_goldore", () -> new WastelandGoldoreBlock());
	public static final RegistryObject<Block> WASTELANDIRONORE = REGISTRY.register("wastelandironore", () -> new WastelandironoreBlock());
	public static final RegistryObject<Block> WASTELANDDIAMONDORE = REGISTRY.register("wastelanddiamondore", () -> new WastelanddiamondoreBlock());
	public static final RegistryObject<Block> WASTELANDEMERALDORE = REGISTRY.register("wastelandemeraldore", () -> new WastelandemeraldoreBlock());
	public static final RegistryObject<Block> WASTELANDLAPISORE = REGISTRY.register("wastelandlapisore", () -> new WastelandlapisoreBlock());
	public static final RegistryObject<Block> WASTELANDREDSTONEORE = REGISTRY.register("wastelandredstoneore", () -> new WastelandredstoneoreBlock());
	public static final RegistryObject<Block> WASTELAND_BROKEN_GLASS = REGISTRY.register("wasteland_broken_glass", () -> new WastelandBrokenGlassBlock());
	public static final RegistryObject<Block> LANDMINE = REGISTRY.register("landmine", () -> new LandmineBlock());
	public static final RegistryObject<Block> WASTELAND_BRICK_WALL = REGISTRY.register("wasteland_brick_wall", () -> new WastelandBrickWallBlock());
	public static final RegistryObject<Block> LOCKER = REGISTRY.register("locker", () -> new LockerBlock());
	public static final RegistryObject<Block> WORN_METAL = REGISTRY.register("worn_metal", () -> new WornMetalBlock());
	public static final RegistryObject<Block> HANGARDOOR = REGISTRY.register("hangardoor", () -> new HangardoorBlock());
	public static final RegistryObject<Block> WASTELAND_CRACKED_BRICK = REGISTRY.register("wasteland_cracked_brick", () -> new WastelandCrackedBrickBlock());
	public static final RegistryObject<Block> WIREFENCE = REGISTRY.register("wirefence", () -> new WirefenceBlock());
	public static final RegistryObject<Block> STRIPPEDMOLDERWOODLOG = REGISTRY.register("strippedmolderwoodlog", () -> new StrippedmolderwoodlogBlock());
	public static final RegistryObject<Block> WASTELANDBRICKS = REGISTRY.register("wastelandbricks", () -> new WastelandbricksBlock());
	public static final RegistryObject<Block> SUBWAYBRICKS = REGISTRY.register("subwaybricks", () -> new SubwaybricksBlock());
	public static final RegistryObject<Block> DOUBLE_SCAFFOLD_BLOCK = REGISTRY.register("double_scaffold_block", () -> new DoubleScaffoldBlockBlock());
	public static final RegistryObject<Block> CAGE = REGISTRY.register("cage", () -> new CageBlock());
	public static final RegistryObject<Block> SCAFFOLDING_WALKWAYS_BLOCK = REGISTRY.register("scaffolding_walkways_block", () -> new ScaffoldingWalkwaysBlockBlock());
	public static final RegistryObject<Block> STEEL_POLE = REGISTRY.register("steel_pole", () -> new SteelPoleBlock());
	public static final RegistryObject<Block> ROOF_METAL = REGISTRY.register("roof_metal", () -> new RoofMetalBlock());
	public static final RegistryObject<Block> BARRICADEPLANKS = REGISTRY.register("barricadeplanks", () -> new BarricadeplanksBlock());
	public static final RegistryObject<Block> REINFORCED_PLANKS = REGISTRY.register("reinforced_planks", () -> new ReinforcedPlanksBlock());
	public static final RegistryObject<Block> SHEETMETALBLOCK = REGISTRY.register("sheetmetalblock", () -> new SheetmetalblockBlock());
	public static final RegistryObject<Block> RUSTY_SHEETMETALBLOCK = REGISTRY.register("rusty_sheetmetalblock", () -> new RustySheetmetalblockBlock());
	public static final RegistryObject<Block> BARRICADESHEETMETALBLOCK = REGISTRY.register("barricadesheetmetalblock", () -> new BarricadesheetmetalblockBlock());
	public static final RegistryObject<Block> BURNISHED_GLASS = REGISTRY.register("burnished_glass", () -> new BurnishedGlassBlock());
	public static final RegistryObject<Block> BLASTED_GLASS = REGISTRY.register("blasted_glass", () -> new BlastedGlassBlock());
	public static final RegistryObject<Block> BLASTED_GLASS_PANE = REGISTRY.register("blasted_glass_pane", () -> new BlastedGlassPaneBlock());
	public static final RegistryObject<Block> BURNISHED_GLASS_PANE = REGISTRY.register("burnished_glass_pane", () -> new BurnishedGlassPaneBlock());
	public static final RegistryObject<Block> WASTELANDTILES = REGISTRY.register("wastelandtiles", () -> new WastelandtilesBlock());
	public static final RegistryObject<Block> BAS_ECORE = REGISTRY.register("bas_ecore", () -> new BASEcoreBlock());
	public static final RegistryObject<Block> MILITARY_METAL_PLATE = REGISTRY.register("military_metal_plate", () -> new MilitaryMetalPlateBlock());
	public static final RegistryObject<Block> MILITARY_METAL_DOOR = REGISTRY.register("military_metal_door", () -> new MilitaryMetalDoorBlock());
	public static final RegistryObject<Block> MILITARY_METALWINDOW = REGISTRY.register("military_metalwindow", () -> new MilitaryMetalwindowBlock());
	public static final RegistryObject<Block> CENTRALUNIT = REGISTRY.register("centralunit", () -> new CentralunitBlock());
	public static final RegistryObject<Block> WASTELANDVENTCONCRETE = REGISTRY.register("wastelandventconcrete", () -> new WastelandventconcreteBlock());
	public static final RegistryObject<Block> LINEDCONCRETE = REGISTRY.register("linedconcrete", () -> new LinedconcreteBlock());
	public static final RegistryObject<Block> WOODEDCONCRETE = REGISTRY.register("woodedconcrete", () -> new WoodedconcreteBlock());
	public static final RegistryObject<Block> HORIZONTALLINEDCONCRETE = REGISTRY.register("horizontallinedconcrete", () -> new HorizontallinedconcreteBlock());
	public static final RegistryObject<Block> GREY_TILES = REGISTRY.register("grey_tiles", () -> new GreyTilesBlock());
	public static final RegistryObject<Block> BLACK_TILES = REGISTRY.register("black_tiles", () -> new BlackTilesBlock());
	public static final RegistryObject<Block> CONCRETE_TILE = REGISTRY.register("concrete_tile", () -> new ConcreteTileBlock());
	public static final RegistryObject<Block> HARDCONCRETE = REGISTRY.register("hardconcrete", () -> new HardconcreteBlock());
	public static final RegistryObject<Block> HARDCONCRETESTAIRS = REGISTRY.register("hardconcretestairs", () -> new HardconcretestairsBlock());
	public static final RegistryObject<Block> RUSTYSHEETMETALSTAIRS = REGISTRY.register("rustysheetmetalstairs", () -> new RustysheetmetalstairsBlock());
	public static final RegistryObject<Block> SHEETMETALSTAIRS = REGISTRY.register("sheetmetalstairs", () -> new SheetmetalstairsBlock());
	public static final RegistryObject<Block> WASTELANDTILESSTAIRS = REGISTRY.register("wastelandtilesstairs", () -> new WastelandtilesstairsBlock());
	public static final RegistryObject<Block> WASTELANDTILESSLAB = REGISTRY.register("wastelandtilesslab", () -> new WastelandtilesslabBlock());
	public static final RegistryObject<Block> WASTELANDHARDSTONE = REGISTRY.register("wastelandhardstone", () -> new WastelandhardstoneBlock());
	public static final RegistryObject<Block> RUST_BLOCK = REGISTRY.register("rust_block", () -> new RustBlockBlock());
	public static final RegistryObject<Block> WASTELAND_ROAD_BLOCK = REGISTRY.register("wasteland_road_block", () -> new WastelandRoadBlockBlock());
	public static final RegistryObject<Block> WASTELAND_ROAD_SLAB = REGISTRY.register("wasteland_road_slab", () -> new WastelandRoadSlabBlock());
	public static final RegistryObject<Block> WORN_METAL_STAIRS = REGISTRY.register("worn_metal_stairs", () -> new WornMetalStairsBlock());
	public static final RegistryObject<Block> WORN_METAL_SLAB = REGISTRY.register("worn_metal_slab", () -> new WornMetalSlabBlock());
	public static final RegistryObject<Block> SCAFFOLDING_WALKWAYSLAB = REGISTRY.register("scaffolding_walkwayslab", () -> new ScaffoldingWalkwayslabBlock());
	public static final RegistryObject<Block> SCAFFOLDING_WALKWAY_STAIRS = REGISTRY.register("scaffolding_walkway_stairs", () -> new ScaffoldingWalkwayStairsBlock());
	public static final RegistryObject<Block> GORE = REGISTRY.register("gore", () -> new GoreBlock());
	public static final RegistryObject<Block> SUPERMUTANTGORE = REGISTRY.register("supermutantgore", () -> new SupermutantgoreBlock());
	public static final RegistryObject<Block> DOUBLE_SCAFFOLD_WALL = REGISTRY.register("double_scaffold_wall", () -> new DoubleScaffoldWallBlock());
	public static final RegistryObject<Block> EXPOSED_RUST_BLOCK = REGISTRY.register("exposed_rust_block", () -> new ExposedRustBlockBlock());
	public static final RegistryObject<Block> MELTED_STEEL_BLOCK = REGISTRY.register("melted_steel_block", () -> new MeltedSteelBlockBlock());
	public static final RegistryObject<Block> MELTED_IRON_BLOCK = REGISTRY.register("melted_iron_block", () -> new MeltedIronBlockBlock());
	public static final RegistryObject<Block> URANIUM_BLOCK = REGISTRY.register("uranium_block", () -> new UraniumBlockBlock());
	public static final RegistryObject<Block> BARBED_WIRES = REGISTRY.register("barbed_wires", () -> new BarbedWiresBlock());
	public static final RegistryObject<Block> WASTELAND_ALUMINUM_ORE = REGISTRY.register("wasteland_aluminum_ore", () -> new WastelandAluminumOreBlock());
	public static final RegistryObject<Block> ALUMINUM_BLOCK = REGISTRY.register("aluminum_block", () -> new AluminumBlockBlock());
	public static final RegistryObject<Block> BOS_DOOR = REGISTRY.register("bos_door", () -> new BosDoorBlock());
	public static final RegistryObject<Block> BOS_METAL_PLATING = REGISTRY.register("bos_metal_plating", () -> new BosMetalPlatingBlock());
	public static final RegistryObject<Block> BOS_METAL_PLATING_LIGHTED = REGISTRY.register("bos_metal_plating_lighted", () -> new BosMetalPlatingLightedBlock());
	public static final RegistryObject<Block> BOS_STEEL_BLOCK = REGISTRY.register("bos_steel_block", () -> new BosSteelBlockBlock());
	public static final RegistryObject<Block> STEEL_BLOCK = REGISTRY.register("steel_block", () -> new SteelBlockBlock());
	public static final RegistryObject<Block> ENCLAVE_DOOR = REGISTRY.register("enclave_door", () -> new EnclaveDoorBlock());
	public static final RegistryObject<Block> ENCLAVE_BUNKER_BLOCK = REGISTRY.register("enclave_bunker_block", () -> new EnclaveBunkerBlockBlock());
	public static final RegistryObject<Block> ENCLAVE_BUNKER_BLOCK_LOGO = REGISTRY.register("enclave_bunker_block_logo", () -> new EnclaveBunkerBlockLogoBlock());
	public static final RegistryObject<Block> ENCLAVE_BUNKER_FLOOR = REGISTRY.register("enclave_bunker_floor", () -> new EnclaveBunkerFloorBlock());
	public static final RegistryObject<Block> BUNKER_BLOCK_LIGHT = REGISTRY.register("bunker_block_light", () -> new BunkerBlockLightBlock());
	public static final RegistryObject<Block> INDUSTRIAL_ALLOY = REGISTRY.register("industrial_alloy", () -> new IndustrialAlloyBlock());
	public static final RegistryObject<Block> INDUSTRIAL_ALLOY_PLAIN = REGISTRY.register("industrial_alloy_plain", () -> new IndustrialAlloyPlainBlock());
	public static final RegistryObject<Block> INDUSTRIAL_ALLOY_SLAB = REGISTRY.register("industrial_alloy_slab", () -> new IndustrialAlloySlabBlock());
	public static final RegistryObject<Block> INDUSTRIAL_ALLOY_STAIR = REGISTRY.register("industrial_alloy_stair", () -> new IndustrialAlloyStairBlock());
	public static final RegistryObject<Block> INDUSTRIAL_ALLOY_WARNING = REGISTRY.register("industrial_alloy_warning", () -> new IndustrialAlloyWarningBlock());
	public static final RegistryObject<Block> INDUSTRIAL_DOOR = REGISTRY.register("industrial_door", () -> new IndustrialDoorBlock());
	public static final RegistryObject<Block> INDUSTRIAL_ALLOW_MID_RIVET = REGISTRY.register("industrial_allow_mid_rivet", () -> new IndustrialAllowMidRivetBlock());
	public static final RegistryObject<Block> INDUSTRIAL_ALLOY_BOTTOM_RIVET = REGISTRY.register("industrial_alloy_bottom_rivet", () -> new IndustrialAlloyBottomRivetBlock());
	public static final RegistryObject<Block> INDUSTRIAL_WALKWAY = REGISTRY.register("industrial_walkway", () -> new IndustrialWalkwayBlock());
	public static final RegistryObject<Block> LEAD_BLOCK = REGISTRY.register("lead_block", () -> new LeadBlockBlock());
	public static final RegistryObject<Block> LEAD_ORE = REGISTRY.register("lead_ore", () -> new LeadOreBlock());
	public static final RegistryObject<Block> MOLTEN_BOXITE = REGISTRY.register("molten_boxite", () -> new MoltenBoxiteBlock());
	public static final RegistryObject<Block> MOLTEN_COPPER = REGISTRY.register("molten_copper", () -> new MoltenCopperBlock());
	public static final RegistryObject<Block> MOLTEN_STEEL = REGISTRY.register("molten_steel", () -> new MoltenSteelBlock());
	public static final RegistryObject<Block> MOLTEN_TIN = REGISTRY.register("molten_tin", () -> new MoltenTinBlock());
	public static final RegistryObject<Block> TIN_BLOCK = REGISTRY.register("tin_block", () -> new TinBlockBlock());
	public static final RegistryObject<Block> URANIUM_ORE = REGISTRY.register("uranium_ore", () -> new UraniumOreBlock());
	public static final RegistryObject<Block> WASTE_SAND = REGISTRY.register("waste_sand", () -> new WasteSandBlock());
	public static final RegistryObject<Block> TIN_ORE = REGISTRY.register("tin_ore", () -> new TinOreBlock());
	public static final RegistryObject<Block> BOS_STEEL_STAIR = REGISTRY.register("bos_steel_stair", () -> new BosSteelStairBlock());
	public static final RegistryObject<Block> STEEL_BARS = REGISTRY.register("steel_bars", () -> new SteelBarsBlock());
	public static final RegistryObject<Block> PLASTER = REGISTRY.register("plaster", () -> new PlasterBlock());
	public static final RegistryObject<Block> OXIDIZED_METAL = REGISTRY.register("oxidized_metal", () -> new OxidizedMetalBlock());
	public static final RegistryObject<Block> OXIDIZED_METAL_STAIR = REGISTRY.register("oxidized_metal_stair", () -> new OxidizedMetalStairBlock());
	public static final RegistryObject<Block> OXIDIZED_METAL_WALL = REGISTRY.register("oxidized_metal_wall", () -> new OxidizedMetalWallBlock());
	public static final RegistryObject<Block> RUINS_BASE = REGISTRY.register("ruins_base", () -> new RuinsBaseBlock());
	public static final RegistryObject<Block> RUINS = REGISTRY.register("ruins", () -> new RuinsBlock());
	public static final RegistryObject<Block> RUINS_GROUND = REGISTRY.register("ruins_ground", () -> new RuinsGroundBlock());
	public static final RegistryObject<Block> INDUSTRIAL_PLATING = REGISTRY.register("industrial_plating", () -> new IndustrialPlatingBlock());
	public static final RegistryObject<Block> INDUSTRIAL_SUPPORT = REGISTRY.register("industrial_support", () -> new IndustrialSupportBlock());
	public static final RegistryObject<Block> SINGLE_SCAFFOLD_BLOCK = REGISTRY.register("single_scaffold_block", () -> new SingleScaffoldBlockBlock());
	public static final RegistryObject<Block> VAULT_WALL = REGISTRY.register("vault_wall", () -> new VaultWallBlock());
	public static final RegistryObject<Block> VAULT_REINFORCED_PILLAR = REGISTRY.register("vault_reinforced_pillar", () -> new VaultReinforcedPillarBlock());
	public static final RegistryObject<Block> VAULT_WALL_CURVED = REGISTRY.register("vault_wall_curved", () -> new VaultWallCurvedBlock());
	public static final RegistryObject<Block> VAULT_WALL_EXPOSED = REGISTRY.register("vault_wall_exposed", () -> new VaultWallExposedBlock());
	public static final RegistryObject<Block> VAULT_FLOOR = REGISTRY.register("vault_floor", () -> new VaultFloorBlock());
	public static final RegistryObject<Block> VAULT_PILLAR = REGISTRY.register("vault_pillar", () -> new VaultPillarBlock());
	public static final RegistryObject<Block> VAULT_VENT = REGISTRY.register("vault_vent", () -> new VaultVentBlock());
	public static final RegistryObject<Block> OXIDIZED_METAL_SLAB = REGISTRY.register("oxidized_metal_slab", () -> new OxidizedMetalSlabBlock());
	public static final RegistryObject<Block> RUSTED_SHEET_METAL_WALL = REGISTRY.register("rusted_sheet_metal_wall", () -> new RustedSheetMetalWallBlock());
	public static final RegistryObject<Block> MILITARY_METAL_PLATE_WALL = REGISTRY.register("military_metal_plate_wall", () -> new MilitaryMetalPlateWallBlock());
	public static final RegistryObject<Block> CHARRED_MOLDER_WOOD_PLANK = REGISTRY.register("charred_molder_wood_plank", () -> new CharredMolderWoodPlankBlock());
	public static final RegistryObject<Block> CHARRED_MOLDER_STAIRS = REGISTRY.register("charred_molder_stairs", () -> new CharredMolderStairsBlock());
	public static final RegistryObject<Block> BOS_STEEL_SLABS = REGISTRY.register("bos_steel_slabs", () -> new BosSteelSlabsBlock());
	public static final RegistryObject<Block> MILITARY_PLATING_SLAB = REGISTRY.register("military_plating_slab", () -> new MilitaryPlatingSlabBlock());
	public static final RegistryObject<Block> MILITARY_METAL_STAIR = REGISTRY.register("military_metal_stair", () -> new MilitaryMetalStairBlock());
	public static final RegistryObject<Block> MILITARY_METAL_HAZARD = REGISTRY.register("military_metal_hazard", () -> new MilitaryMetalHazardBlock());
	public static final RegistryObject<Block> MILITARY_PLATING_WALKWAY = REGISTRY.register("military_plating_walkway", () -> new MilitaryPlatingWalkwayBlock());
	public static final RegistryObject<Block> MILITARY_METAL_RADIATION = REGISTRY.register("military_metal_radiation", () -> new MilitaryMetalRadiationBlock());
	public static final RegistryObject<Block> CHARRED_MOLDER_SLAB = REGISTRY.register("charred_molder_slab", () -> new CharredMolderSlabBlock());
	public static final RegistryObject<Block> CHARRED_MOLDER_FENCE = REGISTRY.register("charred_molder_fence", () -> new CharredMolderFenceBlock());
	public static final RegistryObject<Block> METAL_BARREL = REGISTRY.register("metal_barrel", () -> new MetalBarrelBlock());
	public static final RegistryObject<Block> RADIATION_BARREL = REGISTRY.register("radiation_barrel", () -> new RadiationBarrelBlock());
	public static final RegistryObject<Block> CEILING_LIGHT = REGISTRY.register("ceiling_light", () -> new CeilingLightBlock());
	public static final RegistryObject<Block> FILING_CABINET = REGISTRY.register("filing_cabinet", () -> new FilingCabinetBlock());
	public static final RegistryObject<Block> FLOOR_PAPERS = REGISTRY.register("floor_papers", () -> new FloorPapersBlock());
	public static final RegistryObject<Block> FRIDGE = REGISTRY.register("fridge", () -> new FridgeBlock());
	public static final RegistryObject<Block> MEDICAL_BOX = REGISTRY.register("medical_box", () -> new MedicalBoxBlock());
	public static final RegistryObject<Block> METAL_CHAIR = REGISTRY.register("metal_chair", () -> new MetalChairBlock());
	public static final RegistryObject<Block> MIXER = REGISTRY.register("mixer", () -> new MixerBlock());
	public static final RegistryObject<Block> PIPE = REGISTRY.register("pipe", () -> new PipeBlock());
	public static final RegistryObject<Block> TELEVISION = REGISTRY.register("television", () -> new TelevisionBlock());
	public static final RegistryObject<Block> TERMINAL = REGISTRY.register("terminal", () -> new TerminalBlock());
	public static final RegistryObject<Block> TIRE_STACK = REGISTRY.register("tire_stack", () -> new TireStackBlock());
	public static final RegistryObject<Block> TRASH_BIN = REGISTRY.register("trash_bin", () -> new TrashBinBlock());
	public static final RegistryObject<Block> AMMO_BOX = REGISTRY.register("ammo_box", () -> new AmmoBoxBlock());
	public static final RegistryObject<Block> LIGHT_TUBE = REGISTRY.register("light_tube", () -> new LightTubeBlock());
	public static final RegistryObject<Block> ENCLAVE_BUNKER_STAIRS = REGISTRY.register("enclave_bunker_stairs", () -> new EnclaveBunkerStairsBlock());
	public static final RegistryObject<Block> METAL_SHELF = REGISTRY.register("metal_shelf", () -> new MetalShelfBlock());
	public static final RegistryObject<Block> BOS_METAL_STAIRS = REGISTRY.register("bos_metal_stairs", () -> new BosMetalStairsBlock());
	public static final RegistryObject<Block> WASTELANDDRYDIRT = REGISTRY.register("wastelanddrydirt", () -> new WastelanddrydirtBlock());
	public static final RegistryObject<Block> ROCKYDIRT = REGISTRY.register("rockydirt", () -> new RockydirtBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_ALLOY = REGISTRY.register("grey_industrial_alloy", () -> new GreyIndustrialAlloyBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_ALLOYPLATE = REGISTRY.register("grey_industrial_alloyplate", () -> new GreyIndustrialAlloyplateBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_ALLOWMIDRIVET = REGISTRY.register("grey_industrial_allowmidrivet", () -> new GreyIndustrialAllowmidrivetBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_ALLOYBOTTOMRIVET = REGISTRY.register("grey_industrial_alloybottomrivet", () -> new GreyIndustrialAlloybottomrivetBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_WALKWAY = REGISTRY.register("grey_industrial_walkway", () -> new GreyIndustrialWalkwayBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_WALKWAYSLAB = REGISTRY.register("grey_industrial_walkwayslab", () -> new IndustrialWalkwayslabBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_WALKWAY_STAIRS = REGISTRY.register("grey_industrial_walkway_stairs", () -> new GreyIndustrialWalkwayStairsBlock());
	public static final RegistryObject<Block> INDUSTRIAL_WALKWAYSTAIRS = REGISTRY.register("industrial_walkwaystairs", () -> new IndustrialWalkwaystairsBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_WALKWAY_SLAB = REGISTRY.register("grey_industrial_walkway_slab", () -> new GreyIndustrialWalkwaySlabBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_ALLOY_STAIR = REGISTRY.register("grey_industrial_alloy_stair", () -> new GreyIndustrialAlloyStairBlock());
	public static final RegistryObject<Block> GREY_INDUSTRIAL_ALLOY_SLAB = REGISTRY.register("grey_industrial_alloy_slab", () -> new GreyIndustrialAlloySlabBlock());
	public static final RegistryObject<Block> WASTELAND_BRICKS_SLAB = REGISTRY.register("wasteland_bricks_slab", () -> new WastelandBricksSlabBlock());
	public static final RegistryObject<Block> WASTELAND_BRICKS_STAIRS = REGISTRY.register("wasteland_bricks_stairs", () -> new WastelandBricksStairsBlock());
	public static final RegistryObject<Block> WORN_METAL_PILLAR = REGISTRY.register("worn_metal_pillar", () -> new WornMetalPillarBlock());

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			WastelandgrassblockBlock.blockColorLoad(event);
			WastelandgrassbushBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			WastelandgrassblockBlock.itemColorLoad(event);
			WastelandgrassbushBlock.itemColorLoad(event);
		}
	}
}
