
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.falloutwastelands.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.falloutwastelands.item.WrenchItem;
import net.mcreator.falloutwastelands.item.WonderglueItem;
import net.mcreator.falloutwastelands.item.WineItem;
import net.mcreator.falloutwastelands.item.WhiskeyItem;
import net.mcreator.falloutwastelands.item.WastelandsItem;
import net.mcreator.falloutwastelands.item.WastelandbrickitemItem;
import net.mcreator.falloutwastelands.item.VodkaItem;
import net.mcreator.falloutwastelands.item.VaultSuitItem;
import net.mcreator.falloutwastelands.item.VaultSecuritySuitItem;
import net.mcreator.falloutwastelands.item.VaultHullItem;
import net.mcreator.falloutwastelands.item.VarmintRifleItem;
import net.mcreator.falloutwastelands.item.VaccumTubeItem;
import net.mcreator.falloutwastelands.item.UraniumNuggetItem;
import net.mcreator.falloutwastelands.item.UraniumIngotItem;
import net.mcreator.falloutwastelands.item.TireIronItem;
import net.mcreator.falloutwastelands.item.TinnuggetItem;
import net.mcreator.falloutwastelands.item.TiningotItem;
import net.mcreator.falloutwastelands.item.ThirtytwoammoItem;
import net.mcreator.falloutwastelands.item.TenmmpistolItem;
import net.mcreator.falloutwastelands.item.TenmmhomemadeassaultrifleItem;
import net.mcreator.falloutwastelands.item.TenmmammoItem;
import net.mcreator.falloutwastelands.item.TatoItem;
import net.mcreator.falloutwastelands.item.TaloncombatarmorItem;
import net.mcreator.falloutwastelands.item.T51bPAItem;
import net.mcreator.falloutwastelands.item.T45PAItem;
import net.mcreator.falloutwastelands.item.SuperSledgeItem;
import net.mcreator.falloutwastelands.item.SugarBombsItem;
import net.mcreator.falloutwastelands.item.StrangeMeatPattyItem;
import net.mcreator.falloutwastelands.item.StimpackItem;
import net.mcreator.falloutwastelands.item.SteelnuggetItem;
import net.mcreator.falloutwastelands.item.SteelIngotItem;
import net.mcreator.falloutwastelands.item.SteelCompositeItem;
import net.mcreator.falloutwastelands.item.SmallcalibercasingItem;
import net.mcreator.falloutwastelands.item.SierraMadreMartiniItem;
import net.mcreator.falloutwastelands.item.SecurityBatonItem;
import net.mcreator.falloutwastelands.item.ScrapmetalItem;
import net.mcreator.falloutwastelands.item.ScotchItem;
import net.mcreator.falloutwastelands.item.RollingpinItem;
import net.mcreator.falloutwastelands.item.RoentgenRumItem;
import net.mcreator.falloutwastelands.item.RobcoRepairmanItem;
import net.mcreator.falloutwastelands.item.RoadLeatherItem;
import net.mcreator.falloutwastelands.item.RipperProjectileItem;
import net.mcreator.falloutwastelands.item.RipperItem;
import net.mcreator.falloutwastelands.item.Revolver32Item;
import net.mcreator.falloutwastelands.item.RawUraniumItem;
import net.mcreator.falloutwastelands.item.RawTinItem;
import net.mcreator.falloutwastelands.item.RawLeadItem;
import net.mcreator.falloutwastelands.item.RawAluminumItem;
import net.mcreator.falloutwastelands.item.RaiderdusterItem;
import net.mcreator.falloutwastelands.item.RaiderblastmasterItem;
import net.mcreator.falloutwastelands.item.RaiderbasherItem;
import net.mcreator.falloutwastelands.item.RaiderWarmongerItem;
import net.mcreator.falloutwastelands.item.RadroachMeatItem;
import net.mcreator.falloutwastelands.item.RadiactiveWasteItem;
import net.mcreator.falloutwastelands.item.RadIslandCiderItem;
import net.mcreator.falloutwastelands.item.PsychoItem;
import net.mcreator.falloutwastelands.item.PowerArmorFrameArmorItem;
import net.mcreator.falloutwastelands.item.PotatoCrispsItem;
import net.mcreator.falloutwastelands.item.PlasticsheetItem;
import net.mcreator.falloutwastelands.item.PlasmarifleItem;
import net.mcreator.falloutwastelands.item.PipboyItem;
import net.mcreator.falloutwastelands.item.PAFrameItemItem;
import net.mcreator.falloutwastelands.item.NukaColaQuantumItem;
import net.mcreator.falloutwastelands.item.NukaColaItem;
import net.mcreator.falloutwastelands.item.NoodlesItem;
import net.mcreator.falloutwastelands.item.NinemmpistolItem;
import net.mcreator.falloutwastelands.item.NinemmammoItem;
import net.mcreator.falloutwastelands.item.NeutronadeItem;
import net.mcreator.falloutwastelands.item.NeutronadeCapItem;
import net.mcreator.falloutwastelands.item.NailgunItem;
import net.mcreator.falloutwastelands.item.NailedWrenchItem;
import net.mcreator.falloutwastelands.item.NailItem;
import net.mcreator.falloutwastelands.item.MutlemonItem;
import net.mcreator.falloutwastelands.item.MugItem;
import net.mcreator.falloutwastelands.item.MotorItem;
import net.mcreator.falloutwastelands.item.MotherboardItem;
import net.mcreator.falloutwastelands.item.MirelurkmeatItem;
import net.mcreator.falloutwastelands.item.MirelurkCakeItem;
import net.mcreator.falloutwastelands.item.MilitaryHullItem;
import net.mcreator.falloutwastelands.item.MetalstickItem;
import net.mcreator.falloutwastelands.item.MacheteItem;
import net.mcreator.falloutwastelands.item.LobotomiteSuitItem;
import net.mcreator.falloutwastelands.item.LeadNuggetItem;
import net.mcreator.falloutwastelands.item.LeadIngotItem;
import net.mcreator.falloutwastelands.item.LaserrifleItem;
import net.mcreator.falloutwastelands.item.KnifeItem;
import net.mcreator.falloutwastelands.item.JerricanItem;
import net.mcreator.falloutwastelands.item.InstamashItem;
import net.mcreator.falloutwastelands.item.IndustrialshovelItem;
import net.mcreator.falloutwastelands.item.IndustrialhullItem;
import net.mcreator.falloutwastelands.item.IndustrialhammerItem;
import net.mcreator.falloutwastelands.item.IguanaOnStickItem;
import net.mcreator.falloutwastelands.item.HuntingCasingItem;
import net.mcreator.falloutwastelands.item.HumanBrainItem;
import net.mcreator.falloutwastelands.item.HeavycalibercasingItem;
import net.mcreator.falloutwastelands.item.HandymanSuitItem;
import net.mcreator.falloutwastelands.item.HachetItem;
import net.mcreator.falloutwastelands.item.GeckoEggItem;
import net.mcreator.falloutwastelands.item.GeckoCoockedEggItem;
import net.mcreator.falloutwastelands.item.GammaGulpBeerItem;
import net.mcreator.falloutwastelands.item.FusionCoreItem;
import net.mcreator.falloutwastelands.item.FivemmminigunItem;
import net.mcreator.falloutwastelands.item.FivemmAmmoItem;
import net.mcreator.falloutwastelands.item.FissionBatteryItem;
import net.mcreator.falloutwastelands.item.FertilizerItem;
import net.mcreator.falloutwastelands.item.EnergyCellItem;
import net.mcreator.falloutwastelands.item.EnclaveofficierSuitItem;
import net.mcreator.falloutwastelands.item.EnclaveHullItem;
import net.mcreator.falloutwastelands.item.EnclaveAntiradsuitItem;
import net.mcreator.falloutwastelands.item.EmptyNukaColaBottleItem;
import net.mcreator.falloutwastelands.item.EmptyNeutronadeBottleItem;
import net.mcreator.falloutwastelands.item.DynamiteItemItem;
import net.mcreator.falloutwastelands.item.DentedCanItem;
import net.mcreator.falloutwastelands.item.DeathclawhandItem;
import net.mcreator.falloutwastelands.item.DeathclawGauntletItem;
import net.mcreator.falloutwastelands.item.CramItem;
import net.mcreator.falloutwastelands.item.CornItem;
import net.mcreator.falloutwastelands.item.CopperwiresItem;
import net.mcreator.falloutwastelands.item.CombatarmorItem;
import net.mcreator.falloutwastelands.item.CoffepotItem;
import net.mcreator.falloutwastelands.item.CoffeeItem;
import net.mcreator.falloutwastelands.item.ClothItem;
import net.mcreator.falloutwastelands.item.CigarettepackItem;
import net.mcreator.falloutwastelands.item.ChinesepistolItem;
import net.mcreator.falloutwastelands.item.ChicagoOmeletteItem;
import net.mcreator.falloutwastelands.item.CattleRodItem;
import net.mcreator.falloutwastelands.item.CannedBeefItem;
import net.mcreator.falloutwastelands.item.BrotherhoodHullItem;
import net.mcreator.falloutwastelands.item.BrahimMeatItem;
import net.mcreator.falloutwastelands.item.BottleCapItem;
import net.mcreator.falloutwastelands.item.BloatFlyMeatItem;
import net.mcreator.falloutwastelands.item.BeerItem;
import net.mcreator.falloutwastelands.item.BaseballClubItem;
import net.mcreator.falloutwastelands.item.BaseballBatItem;
import net.mcreator.falloutwastelands.item.BaseGunItemItem;
import net.mcreator.falloutwastelands.item.BASENameItemItem;
import net.mcreator.falloutwastelands.item.BASECapBundleItem;
import net.mcreator.falloutwastelands.item.AsbestosItem;
import net.mcreator.falloutwastelands.item.ArmyRepairmanSuitItem;
import net.mcreator.falloutwastelands.item.AntiradsuitItem;
import net.mcreator.falloutwastelands.item.AntiradclothingItem;
import net.mcreator.falloutwastelands.item.AluminumIngotItem;
import net.mcreator.falloutwastelands.item.AluminiumnuggetItem;
import net.mcreator.falloutwastelands.item.AdvancedMotorItem;
import net.mcreator.falloutwastelands.item.AdvancedMotherboardItem;
import net.mcreator.falloutwastelands.item.AcidItem;
import net.mcreator.falloutwastelands.item.AbsintheItem;
import net.mcreator.falloutwastelands.item.AbraxoCleanerItem;
import net.mcreator.falloutwastelands.block.display.BASEcoreDisplayItem;
import net.mcreator.falloutwastelands.FalloutWastelandsMod;

public class FalloutWastelandsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, FalloutWastelandsMod.MODID);
	public static final RegistryObject<Item> WASTELAND_DIRT = block(FalloutWastelandsModBlocks.WASTELAND_DIRT);
	public static final RegistryObject<Item> WASTELAND_STONE = block(FalloutWastelandsModBlocks.WASTELAND_STONE);
	public static final RegistryObject<Item> WASTELANDS = REGISTRY.register("wastelands", () -> new WastelandsItem());
	public static final RegistryObject<Item> WASTELANDGRASSBLOCK = block(FalloutWastelandsModBlocks.WASTELANDGRASSBLOCK);
	public static final RegistryObject<Item> CRACKED_WASTELAND_CONCRETE_WALL = block(FalloutWastelandsModBlocks.CRACKED_WASTELAND_CONCRETE_WALL);
	public static final RegistryObject<Item> MOLDER_WOOD_BUTTON = block(FalloutWastelandsModBlocks.MOLDER_WOOD_BUTTON);
	public static final RegistryObject<Item> WASTELAND_CONCRETE_STAIRS = block(FalloutWastelandsModBlocks.WASTELAND_CONCRETE_STAIRS);
	public static final RegistryObject<Item> MOLDER_WOOD_PRESSURE_PLATE = block(FalloutWastelandsModBlocks.MOLDER_WOOD_PRESSURE_PLATE);
	public static final RegistryObject<Item> WASTELAND_ROOTY_DIRT = block(FalloutWastelandsModBlocks.WASTELAND_ROOTY_DIRT);
	public static final RegistryObject<Item> MOLDER_WOOD_LOG = block(FalloutWastelandsModBlocks.MOLDER_WOOD_LOG);
	public static final RegistryObject<Item> CRACKED_WASTELAND_CONCRETE = block(FalloutWastelandsModBlocks.CRACKED_WASTELAND_CONCRETE);
	public static final RegistryObject<Item> MOLDER_WOOD_DOOR = doubleBlock(FalloutWastelandsModBlocks.MOLDER_WOOD_DOOR);
	public static final RegistryObject<Item> THE_GLOW_DIRT = block(FalloutWastelandsModBlocks.THE_GLOW_DIRT);
	public static final RegistryObject<Item> MOLDER_WOOD_TRAPDOOR = block(FalloutWastelandsModBlocks.MOLDER_WOOD_TRAPDOOR);
	public static final RegistryObject<Item> SLAB_WASTELAND_COBBLESTONE = block(FalloutWastelandsModBlocks.SLAB_WASTELAND_COBBLESTONE);
	public static final RegistryObject<Item> WASTELAND_COBBLESTONE = block(FalloutWastelandsModBlocks.WASTELAND_COBBLESTONE);
	public static final RegistryObject<Item> STAIR_WASTELAND_COBBLESTONE = block(FalloutWastelandsModBlocks.STAIR_WASTELAND_COBBLESTONE);
	public static final RegistryObject<Item> WASTELAND_CONCRETE = block(FalloutWastelandsModBlocks.WASTELAND_CONCRETE);
	public static final RegistryObject<Item> MOLDER_WOOD_STAIRS = block(FalloutWastelandsModBlocks.MOLDER_WOOD_STAIRS);
	public static final RegistryObject<Item> CRACKED_WASTELAND_CONCRETE_STAIRS = block(FalloutWastelandsModBlocks.CRACKED_WASTELAND_CONCRETE_STAIRS);
	public static final RegistryObject<Item> MOLDER_WOOD_PLANKS = block(FalloutWastelandsModBlocks.MOLDER_WOOD_PLANKS);
	public static final RegistryObject<Item> WASTELAND_BRICK = block(FalloutWastelandsModBlocks.WASTELAND_BRICK);
	public static final RegistryObject<Item> MOLDER_WOOD_FENCE = block(FalloutWastelandsModBlocks.MOLDER_WOOD_FENCE);
	public static final RegistryObject<Item> WASTELAND_CONCRETE_WALL = block(FalloutWastelandsModBlocks.WASTELAND_CONCRETE_WALL);
	public static final RegistryObject<Item> MOLDER_WOOD_WOOD = block(FalloutWastelandsModBlocks.MOLDER_WOOD_WOOD);
	public static final RegistryObject<Item> CRACKED_WASTELAND_CONCRETE_SLABS = block(FalloutWastelandsModBlocks.CRACKED_WASTELAND_CONCRETE_SLABS);
	public static final RegistryObject<Item> MOLDER_WOOD_SLAB = block(FalloutWastelandsModBlocks.MOLDER_WOOD_SLAB);
	public static final RegistryObject<Item> WALL_WASTELAND_COBBLESTONE = block(FalloutWastelandsModBlocks.WALL_WASTELAND_COBBLESTONE);
	public static final RegistryObject<Item> MOLDER_WOOD_FENCE_GATE = block(FalloutWastelandsModBlocks.MOLDER_WOOD_FENCE_GATE);
	public static final RegistryObject<Item> WASTELAND_CONCRETE_SLAB = block(FalloutWastelandsModBlocks.WASTELAND_CONCRETE_SLAB);
	public static final RegistryObject<Item> WASTELANDGRASSBUSH = block(FalloutWastelandsModBlocks.WASTELANDGRASSBUSH);
	public static final RegistryObject<Item> WASTELANDBURNTGRASS = block(FalloutWastelandsModBlocks.WASTELANDBURNTGRASS);
	public static final RegistryObject<Item> WASTELANDSHORTBURNTGRASS = block(FalloutWastelandsModBlocks.WASTELANDSHORTBURNTGRASS);
	public static final RegistryObject<Item> WASTELAND_BRICK_STAIRS = block(FalloutWastelandsModBlocks.WASTELAND_BRICK_STAIRS);
	public static final RegistryObject<Item> WASTELAND_BRICKSLAB = block(FalloutWastelandsModBlocks.WASTELAND_BRICKSLAB);
	public static final RegistryObject<Item> WASTELANDPEBBLE = block(FalloutWastelandsModBlocks.WASTELANDPEBBLE);
	public static final RegistryObject<Item> WASTELANDGRAVEL = block(FalloutWastelandsModBlocks.WASTELANDGRAVEL);
	public static final RegistryObject<Item> WASTELANDCOALORE = block(FalloutWastelandsModBlocks.WASTELANDCOALORE);
	public static final RegistryObject<Item> WASTELANDCOPPERORE = block(FalloutWastelandsModBlocks.WASTELANDCOPPERORE);
	public static final RegistryObject<Item> WASTELAND_GOLDORE = block(FalloutWastelandsModBlocks.WASTELAND_GOLDORE);
	public static final RegistryObject<Item> RAIDERDUSTER_HELMET = REGISTRY.register("raiderduster_helmet", () -> new RaiderdusterItem.Helmet());
	public static final RegistryObject<Item> RAIDERDUSTER_CHESTPLATE = REGISTRY.register("raiderduster_chestplate", () -> new RaiderdusterItem.Chestplate());
	public static final RegistryObject<Item> RAIDERDUSTER_LEGGINGS = REGISTRY.register("raiderduster_leggings", () -> new RaiderdusterItem.Leggings());
	public static final RegistryObject<Item> RAIDERDUSTER_BOOTS = REGISTRY.register("raiderduster_boots", () -> new RaiderdusterItem.Boots());
	public static final RegistryObject<Item> WASTELANDIRONORE = block(FalloutWastelandsModBlocks.WASTELANDIRONORE);
	public static final RegistryObject<Item> WASTELANDDIAMONDORE = block(FalloutWastelandsModBlocks.WASTELANDDIAMONDORE);
	public static final RegistryObject<Item> WASTELANDEMERALDORE = block(FalloutWastelandsModBlocks.WASTELANDEMERALDORE);
	public static final RegistryObject<Item> WASTELANDLAPISORE = block(FalloutWastelandsModBlocks.WASTELANDLAPISORE);
	public static final RegistryObject<Item> WASTELANDREDSTONEORE = block(FalloutWastelandsModBlocks.WASTELANDREDSTONEORE);
	public static final RegistryObject<Item> CLOTH = REGISTRY.register("cloth", () -> new ClothItem());
	public static final RegistryObject<Item> WASTELAND_BROKEN_GLASS = block(FalloutWastelandsModBlocks.WASTELAND_BROKEN_GLASS);
	public static final RegistryObject<Item> LANDMINE = block(FalloutWastelandsModBlocks.LANDMINE);
	public static final RegistryObject<Item> WASTELAND_BRICK_WALL = block(FalloutWastelandsModBlocks.WASTELAND_BRICK_WALL);
	public static final RegistryObject<Item> LOCKER = block(FalloutWastelandsModBlocks.LOCKER);
	public static final RegistryObject<Item> TATO = REGISTRY.register("tato", () -> new TatoItem());
	public static final RegistryObject<Item> RAIDERBASHER_HELMET = REGISTRY.register("raiderbasher_helmet", () -> new RaiderbasherItem.Helmet());
	public static final RegistryObject<Item> RAIDERBASHER_CHESTPLATE = REGISTRY.register("raiderbasher_chestplate", () -> new RaiderbasherItem.Chestplate());
	public static final RegistryObject<Item> RAIDERBASHER_LEGGINGS = REGISTRY.register("raiderbasher_leggings", () -> new RaiderbasherItem.Leggings());
	public static final RegistryObject<Item> RAIDERBASHER_BOOTS = REGISTRY.register("raiderbasher_boots", () -> new RaiderbasherItem.Boots());
	public static final RegistryObject<Item> RAIDERBLASTMASTER_HELMET = REGISTRY.register("raiderblastmaster_helmet", () -> new RaiderblastmasterItem.Helmet());
	public static final RegistryObject<Item> RAIDERBLASTMASTER_CHESTPLATE = REGISTRY.register("raiderblastmaster_chestplate", () -> new RaiderblastmasterItem.Chestplate());
	public static final RegistryObject<Item> RAIDERBLASTMASTER_LEGGINGS = REGISTRY.register("raiderblastmaster_leggings", () -> new RaiderblastmasterItem.Leggings());
	public static final RegistryObject<Item> RAIDERBLASTMASTER_BOOTS = REGISTRY.register("raiderblastmaster_boots", () -> new RaiderblastmasterItem.Boots());
	public static final RegistryObject<Item> WORN_METAL = block(FalloutWastelandsModBlocks.WORN_METAL);
	public static final RegistryObject<Item> HANGARDOOR = doubleBlock(FalloutWastelandsModBlocks.HANGARDOOR);
	public static final RegistryObject<Item> WASTELAND_CRACKED_BRICK = block(FalloutWastelandsModBlocks.WASTELAND_CRACKED_BRICK);
	public static final RegistryObject<Item> ASBESTOS = REGISTRY.register("asbestos", () -> new AsbestosItem());
	public static final RegistryObject<Item> ANTIRADCLOTHING = REGISTRY.register("antiradclothing", () -> new AntiradclothingItem());
	public static final RegistryObject<Item> WIREFENCE = block(FalloutWastelandsModBlocks.WIREFENCE);
	public static final RegistryObject<Item> COPPERWIRES = REGISTRY.register("copperwires", () -> new CopperwiresItem());
	public static final RegistryObject<Item> JERRICAN = REGISTRY.register("jerrican", () -> new JerricanItem());
	public static final RegistryObject<Item> COMBATARMOR_HELMET = REGISTRY.register("combatarmor_helmet", () -> new CombatarmorItem.Helmet());
	public static final RegistryObject<Item> COMBATARMOR_CHESTPLATE = REGISTRY.register("combatarmor_chestplate", () -> new CombatarmorItem.Chestplate());
	public static final RegistryObject<Item> COMBATARMOR_LEGGINGS = REGISTRY.register("combatarmor_leggings", () -> new CombatarmorItem.Leggings());
	public static final RegistryObject<Item> COMBATARMOR_BOOTS = REGISTRY.register("combatarmor_boots", () -> new CombatarmorItem.Boots());
	public static final RegistryObject<Item> REVOLVER_32 = REGISTRY.register("revolver_32", () -> new Revolver32Item());
	public static final RegistryObject<Item> STRIPPEDMOLDERWOODLOG = block(FalloutWastelandsModBlocks.STRIPPEDMOLDERWOODLOG);
	public static final RegistryObject<Item> WASTELANDBRICKS = block(FalloutWastelandsModBlocks.WASTELANDBRICKS);
	public static final RegistryObject<Item> SUBWAYBRICKS = block(FalloutWastelandsModBlocks.SUBWAYBRICKS);
	public static final RegistryObject<Item> DOUBLE_SCAFFOLD_BLOCK = block(FalloutWastelandsModBlocks.DOUBLE_SCAFFOLD_BLOCK);
	public static final RegistryObject<Item> CAGE = block(FalloutWastelandsModBlocks.CAGE);
	public static final RegistryObject<Item> SCAFFOLDING_WALKWAYS_BLOCK = block(FalloutWastelandsModBlocks.SCAFFOLDING_WALKWAYS_BLOCK);
	public static final RegistryObject<Item> WASTELANDBRICKITEM = REGISTRY.register("wastelandbrickitem", () -> new WastelandbrickitemItem());
	public static final RegistryObject<Item> STEEL_POLE = block(FalloutWastelandsModBlocks.STEEL_POLE);
	public static final RegistryObject<Item> ROOF_METAL = block(FalloutWastelandsModBlocks.ROOF_METAL);
	public static final RegistryObject<Item> BARRICADEPLANKS = block(FalloutWastelandsModBlocks.BARRICADEPLANKS);
	public static final RegistryObject<Item> REINFORCED_PLANKS = block(FalloutWastelandsModBlocks.REINFORCED_PLANKS);
	public static final RegistryObject<Item> SHEETMETALBLOCK = block(FalloutWastelandsModBlocks.SHEETMETALBLOCK);
	public static final RegistryObject<Item> RUSTY_SHEETMETALBLOCK = block(FalloutWastelandsModBlocks.RUSTY_SHEETMETALBLOCK);
	public static final RegistryObject<Item> BARRICADESHEETMETALBLOCK = block(FalloutWastelandsModBlocks.BARRICADESHEETMETALBLOCK);
	public static final RegistryObject<Item> BURNISHED_GLASS = block(FalloutWastelandsModBlocks.BURNISHED_GLASS);
	public static final RegistryObject<Item> BLASTED_GLASS = block(FalloutWastelandsModBlocks.BLASTED_GLASS);
	public static final RegistryObject<Item> BLASTED_GLASS_PANE = block(FalloutWastelandsModBlocks.BLASTED_GLASS_PANE);
	public static final RegistryObject<Item> BURNISHED_GLASS_PANE = block(FalloutWastelandsModBlocks.BURNISHED_GLASS_PANE);
	public static final RegistryObject<Item> TININGOT = REGISTRY.register("tiningot", () -> new TiningotItem());
	public static final RegistryObject<Item> ALUMINUM_INGOT = REGISTRY.register("aluminum_ingot", () -> new AluminumIngotItem());
	public static final RegistryObject<Item> STEEL_INGOT = REGISTRY.register("steel_ingot", () -> new SteelIngotItem());
	public static final RegistryObject<Item> LEAD_INGOT = REGISTRY.register("lead_ingot", () -> new LeadIngotItem());
	public static final RegistryObject<Item> URANIUM_INGOT = REGISTRY.register("uranium_ingot", () -> new UraniumIngotItem());
	public static final RegistryObject<Item> NUKA_COLA = REGISTRY.register("nuka_cola", () -> new NukaColaItem());
	public static final RegistryObject<Item> EMPTY_NUKA_COLA_BOTTLE = REGISTRY.register("empty_nuka_cola_bottle", () -> new EmptyNukaColaBottleItem());
	public static final RegistryObject<Item> NUKA_COLA_QUANTUM = REGISTRY.register("nuka_cola_quantum", () -> new NukaColaQuantumItem());
	public static final RegistryObject<Item> BOTTLE_CAP = REGISTRY.register("bottle_cap", () -> new BottleCapItem());
	public static final RegistryObject<Item> NINEMMPISTOL = REGISTRY.register("ninemmpistol", () -> new NinemmpistolItem());
	public static final RegistryObject<Item> NEUTRONADE = REGISTRY.register("neutronade", () -> new NeutronadeItem());
	public static final RegistryObject<Item> NEUTRONADE_CAP = REGISTRY.register("neutronade_cap", () -> new NeutronadeCapItem());
	public static final RegistryObject<Item> EMPTY_NEUTRONADE_BOTTLE = REGISTRY.register("empty_neutronade_bottle", () -> new EmptyNeutronadeBottleItem());
	public static final RegistryObject<Item> CANNIBAL_00_SPAWN_EGG = REGISTRY.register("cannibal_00_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.CANNIBAL_00, -11382217, -8687268, new Item.Properties()));
	public static final RegistryObject<Item> WASTELANDTILES = block(FalloutWastelandsModBlocks.WASTELANDTILES);
	public static final RegistryObject<Item> BAS_ECORE = REGISTRY.register(FalloutWastelandsModBlocks.BAS_ECORE.getId().getPath(), () -> new BASEcoreDisplayItem(FalloutWastelandsModBlocks.BAS_ECORE.get(), new Item.Properties()));
	public static final RegistryObject<Item> BASE_CAP_BUNDLE = REGISTRY.register("base_cap_bundle", () -> new BASECapBundleItem());
	public static final RegistryObject<Item> BASE_NAME_ITEM = REGISTRY.register("base_name_item", () -> new BASENameItemItem());
	public static final RegistryObject<Item> MILITARY_METAL_PLATE = block(FalloutWastelandsModBlocks.MILITARY_METAL_PLATE);
	public static final RegistryObject<Item> MILITARY_METAL_DOOR = doubleBlock(FalloutWastelandsModBlocks.MILITARY_METAL_DOOR);
	public static final RegistryObject<Item> SCRAPMETAL = REGISTRY.register("scrapmetal", () -> new ScrapmetalItem());
	public static final RegistryObject<Item> STIMPACK = REGISTRY.register("stimpack", () -> new StimpackItem());
	public static final RegistryObject<Item> PSYCHO = REGISTRY.register("psycho", () -> new PsychoItem());
	public static final RegistryObject<Item> ANTIRADSUIT_HELMET = REGISTRY.register("antiradsuit_helmet", () -> new AntiradsuitItem.Helmet());
	public static final RegistryObject<Item> ANTIRADSUIT_CHESTPLATE = REGISTRY.register("antiradsuit_chestplate", () -> new AntiradsuitItem.Chestplate());
	public static final RegistryObject<Item> ANTIRADSUIT_LEGGINGS = REGISTRY.register("antiradsuit_leggings", () -> new AntiradsuitItem.Leggings());
	public static final RegistryObject<Item> ANTIRADSUIT_BOOTS = REGISTRY.register("antiradsuit_boots", () -> new AntiradsuitItem.Boots());
	public static final RegistryObject<Item> TALONCOMBATARMOR_HELMET = REGISTRY.register("taloncombatarmor_helmet", () -> new TaloncombatarmorItem.Helmet());
	public static final RegistryObject<Item> TALONCOMBATARMOR_CHESTPLATE = REGISTRY.register("taloncombatarmor_chestplate", () -> new TaloncombatarmorItem.Chestplate());
	public static final RegistryObject<Item> TALONCOMBATARMOR_LEGGINGS = REGISTRY.register("taloncombatarmor_leggings", () -> new TaloncombatarmorItem.Leggings());
	public static final RegistryObject<Item> TALONCOMBATARMOR_BOOTS = REGISTRY.register("taloncombatarmor_boots", () -> new TaloncombatarmorItem.Boots());
	public static final RegistryObject<Item> PIPBOY = REGISTRY.register("pipboy", () -> new PipboyItem());
	public static final RegistryObject<Item> MILITARY_METALWINDOW = block(FalloutWastelandsModBlocks.MILITARY_METALWINDOW);
	public static final RegistryObject<Item> CENTRALUNIT = block(FalloutWastelandsModBlocks.CENTRALUNIT);
	public static final RegistryObject<Item> WASTELANDVENTCONCRETE = block(FalloutWastelandsModBlocks.WASTELANDVENTCONCRETE);
	public static final RegistryObject<Item> LINEDCONCRETE = block(FalloutWastelandsModBlocks.LINEDCONCRETE);
	public static final RegistryObject<Item> WOODEDCONCRETE = block(FalloutWastelandsModBlocks.WOODEDCONCRETE);
	public static final RegistryObject<Item> HORIZONTALLINEDCONCRETE = block(FalloutWastelandsModBlocks.HORIZONTALLINEDCONCRETE);
	public static final RegistryObject<Item> GREY_TILES = block(FalloutWastelandsModBlocks.GREY_TILES);
	public static final RegistryObject<Item> BLACK_TILES = block(FalloutWastelandsModBlocks.BLACK_TILES);
	public static final RegistryObject<Item> CONCRETE_TILE = block(FalloutWastelandsModBlocks.CONCRETE_TILE);
	public static final RegistryObject<Item> HARDCONCRETE = block(FalloutWastelandsModBlocks.HARDCONCRETE);
	public static final RegistryObject<Item> HARDCONCRETESTAIRS = block(FalloutWastelandsModBlocks.HARDCONCRETESTAIRS);
	public static final RegistryObject<Item> RUSTYSHEETMETALSTAIRS = block(FalloutWastelandsModBlocks.RUSTYSHEETMETALSTAIRS);
	public static final RegistryObject<Item> SHEETMETALSTAIRS = block(FalloutWastelandsModBlocks.SHEETMETALSTAIRS);
	public static final RegistryObject<Item> WASTELANDTILESSTAIRS = block(FalloutWastelandsModBlocks.WASTELANDTILESSTAIRS);
	public static final RegistryObject<Item> WASTELANDTILESSLAB = block(FalloutWastelandsModBlocks.WASTELANDTILESSLAB);
	public static final RegistryObject<Item> WASTELANDHARDSTONE = block(FalloutWastelandsModBlocks.WASTELANDHARDSTONE);
	public static final RegistryObject<Item> RUST_BLOCK = block(FalloutWastelandsModBlocks.RUST_BLOCK);
	public static final RegistryObject<Item> WASTELAND_ROAD_BLOCK = block(FalloutWastelandsModBlocks.WASTELAND_ROAD_BLOCK);
	public static final RegistryObject<Item> WASTELAND_ROAD_SLAB = block(FalloutWastelandsModBlocks.WASTELAND_ROAD_SLAB);
	public static final RegistryObject<Item> WORN_METAL_STAIRS = block(FalloutWastelandsModBlocks.WORN_METAL_STAIRS);
	public static final RegistryObject<Item> WORN_METAL_SLAB = block(FalloutWastelandsModBlocks.WORN_METAL_SLAB);
	public static final RegistryObject<Item> SCAFFOLDING_WALKWAYSLAB = block(FalloutWastelandsModBlocks.SCAFFOLDING_WALKWAYSLAB);
	public static final RegistryObject<Item> SCAFFOLDING_WALKWAY_STAIRS = block(FalloutWastelandsModBlocks.SCAFFOLDING_WALKWAY_STAIRS);
	public static final RegistryObject<Item> GORE = block(FalloutWastelandsModBlocks.GORE);
	public static final RegistryObject<Item> SUPERMUTANTGORE = block(FalloutWastelandsModBlocks.SUPERMUTANTGORE);
	public static final RegistryObject<Item> DOUBLE_SCAFFOLD_WALL = block(FalloutWastelandsModBlocks.DOUBLE_SCAFFOLD_WALL);
	public static final RegistryObject<Item> EXPOSED_RUST_BLOCK = block(FalloutWastelandsModBlocks.EXPOSED_RUST_BLOCK);
	public static final RegistryObject<Item> MELTED_STEEL_BLOCK = block(FalloutWastelandsModBlocks.MELTED_STEEL_BLOCK);
	public static final RegistryObject<Item> MELTED_IRON_BLOCK = block(FalloutWastelandsModBlocks.MELTED_IRON_BLOCK);
	public static final RegistryObject<Item> URANIUM_BLOCK = block(FalloutWastelandsModBlocks.URANIUM_BLOCK);
	public static final RegistryObject<Item> BARBED_WIRES = block(FalloutWastelandsModBlocks.BARBED_WIRES);
	public static final RegistryObject<Item> TENMMPISTOL = REGISTRY.register("tenmmpistol", () -> new TenmmpistolItem());
	public static final RegistryObject<Item> TENMMAMMO = REGISTRY.register("tenmmammo", () -> new TenmmammoItem());
	public static final RegistryObject<Item> NINEMMAMMO = REGISTRY.register("ninemmammo", () -> new NinemmammoItem());
	public static final RegistryObject<Item> TENMMHOMEMADEASSAULTRIFLE = REGISTRY.register("tenmmhomemadeassaultrifle", () -> new TenmmhomemadeassaultrifleItem());
	public static final RegistryObject<Item> FIVEMM_AMMO = REGISTRY.register("fivemm_ammo", () -> new FivemmAmmoItem());
	public static final RegistryObject<Item> WRENCH = REGISTRY.register("wrench", () -> new WrenchItem());
	public static final RegistryObject<Item> LASERRIFLE = REGISTRY.register("laserrifle", () -> new LaserrifleItem());
	public static final RegistryObject<Item> CORN = REGISTRY.register("corn", () -> new CornItem());
	public static final RegistryObject<Item> NAILED_WRENCH = REGISTRY.register("nailed_wrench", () -> new NailedWrenchItem());
	public static final RegistryObject<Item> INDUSTRIALSHOVEL = REGISTRY.register("industrialshovel", () -> new IndustrialshovelItem());
	public static final RegistryObject<Item> PLASMARIFLE = REGISTRY.register("plasmarifle", () -> new PlasmarifleItem());
	public static final RegistryObject<Item> NAILGUN = REGISTRY.register("nailgun", () -> new NailgunItem());
	public static final RegistryObject<Item> ROLLINGPIN = REGISTRY.register("rollingpin", () -> new RollingpinItem());
	public static final RegistryObject<Item> CHINESEPISTOL = REGISTRY.register("chinesepistol", () -> new ChinesepistolItem());
	public static final RegistryObject<Item> HACHET = REGISTRY.register("hachet", () -> new HachetItem());
	public static final RegistryObject<Item> THIRTYTWOAMMO = REGISTRY.register("thirtytwoammo", () -> new ThirtytwoammoItem());
	public static final RegistryObject<Item> NAIL = REGISTRY.register("nail", () -> new NailItem());
	public static final RegistryObject<Item> INDUSTRIALHAMMER = REGISTRY.register("industrialhammer", () -> new IndustrialhammerItem());
	public static final RegistryObject<Item> ENERGY_CELL = REGISTRY.register("energy_cell", () -> new EnergyCellItem());
	public static final RegistryObject<Item> TIRE_IRON = REGISTRY.register("tire_iron", () -> new TireIronItem());
	public static final RegistryObject<Item> FIVEMMMINIGUN = REGISTRY.register("fivemmminigun", () -> new FivemmminigunItem());
	public static final RegistryObject<Item> RIPPER = REGISTRY.register("ripper", () -> new RipperItem());
	public static final RegistryObject<Item> WASTELAND_ALUMINUM_ORE = block(FalloutWastelandsModBlocks.WASTELAND_ALUMINUM_ORE);
	public static final RegistryObject<Item> ALUMINUM_BLOCK = block(FalloutWastelandsModBlocks.ALUMINUM_BLOCK);
	public static final RegistryObject<Item> BOS_DOOR = doubleBlock(FalloutWastelandsModBlocks.BOS_DOOR);
	public static final RegistryObject<Item> BOS_METAL_PLATING = block(FalloutWastelandsModBlocks.BOS_METAL_PLATING);
	public static final RegistryObject<Item> BOS_METAL_PLATING_LIGHTED = block(FalloutWastelandsModBlocks.BOS_METAL_PLATING_LIGHTED);
	public static final RegistryObject<Item> BOS_STEEL_BLOCK = block(FalloutWastelandsModBlocks.BOS_STEEL_BLOCK);
	public static final RegistryObject<Item> STEEL_BLOCK = block(FalloutWastelandsModBlocks.STEEL_BLOCK);
	public static final RegistryObject<Item> ENCLAVE_DOOR = doubleBlock(FalloutWastelandsModBlocks.ENCLAVE_DOOR);
	public static final RegistryObject<Item> ENCLAVE_BUNKER_BLOCK = block(FalloutWastelandsModBlocks.ENCLAVE_BUNKER_BLOCK);
	public static final RegistryObject<Item> ENCLAVE_BUNKER_BLOCK_LOGO = block(FalloutWastelandsModBlocks.ENCLAVE_BUNKER_BLOCK_LOGO);
	public static final RegistryObject<Item> ENCLAVE_BUNKER_FLOOR = block(FalloutWastelandsModBlocks.ENCLAVE_BUNKER_FLOOR);
	public static final RegistryObject<Item> BUNKER_BLOCK_LIGHT = block(FalloutWastelandsModBlocks.BUNKER_BLOCK_LIGHT);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY_PLAIN = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY_PLAIN);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY_SLAB = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY_SLAB);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY_STAIR = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY_STAIR);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY_WARNING = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY_WARNING);
	public static final RegistryObject<Item> INDUSTRIAL_DOOR = doubleBlock(FalloutWastelandsModBlocks.INDUSTRIAL_DOOR);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOW_MID_RIVET = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOW_MID_RIVET);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY_BOTTOM_RIVET = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY_BOTTOM_RIVET);
	public static final RegistryObject<Item> INDUSTRIAL_WALKWAY = block(FalloutWastelandsModBlocks.INDUSTRIAL_WALKWAY);
	public static final RegistryObject<Item> LEAD_BLOCK = block(FalloutWastelandsModBlocks.LEAD_BLOCK);
	public static final RegistryObject<Item> LEAD_ORE = block(FalloutWastelandsModBlocks.LEAD_ORE);
	public static final RegistryObject<Item> RAW_LEAD = REGISTRY.register("raw_lead", () -> new RawLeadItem());
	public static final RegistryObject<Item> RAW_ALUMINUM = REGISTRY.register("raw_aluminum", () -> new RawAluminumItem());
	public static final RegistryObject<Item> MOLTEN_BOXITE = block(FalloutWastelandsModBlocks.MOLTEN_BOXITE);
	public static final RegistryObject<Item> MOLTEN_COPPER = block(FalloutWastelandsModBlocks.MOLTEN_COPPER);
	public static final RegistryObject<Item> MOLTEN_STEEL = block(FalloutWastelandsModBlocks.MOLTEN_STEEL);
	public static final RegistryObject<Item> MOLTEN_TIN = block(FalloutWastelandsModBlocks.MOLTEN_TIN);
	public static final RegistryObject<Item> TIN_BLOCK = block(FalloutWastelandsModBlocks.TIN_BLOCK);
	public static final RegistryObject<Item> URANIUM_ORE = block(FalloutWastelandsModBlocks.URANIUM_ORE);
	public static final RegistryObject<Item> RAW_URANIUM = REGISTRY.register("raw_uranium", () -> new RawUraniumItem());
	public static final RegistryObject<Item> WASTE_SAND = block(FalloutWastelandsModBlocks.WASTE_SAND);
	public static final RegistryObject<Item> TIN_ORE = block(FalloutWastelandsModBlocks.TIN_ORE);
	public static final RegistryObject<Item> RAW_TIN = REGISTRY.register("raw_tin", () -> new RawTinItem());
	public static final RegistryObject<Item> BOS_STEEL_STAIR = block(FalloutWastelandsModBlocks.BOS_STEEL_STAIR);
	public static final RegistryObject<Item> STEEL_BARS = block(FalloutWastelandsModBlocks.STEEL_BARS);
	public static final RegistryObject<Item> PLASTER = block(FalloutWastelandsModBlocks.PLASTER);
	public static final RegistryObject<Item> OXIDIZED_METAL = block(FalloutWastelandsModBlocks.OXIDIZED_METAL);
	public static final RegistryObject<Item> OXIDIZED_METAL_STAIR = block(FalloutWastelandsModBlocks.OXIDIZED_METAL_STAIR);
	public static final RegistryObject<Item> OXIDIZED_METAL_WALL = block(FalloutWastelandsModBlocks.OXIDIZED_METAL_WALL);
	public static final RegistryObject<Item> RUINS_BASE = block(FalloutWastelandsModBlocks.RUINS_BASE);
	public static final RegistryObject<Item> RUINS = block(FalloutWastelandsModBlocks.RUINS);
	public static final RegistryObject<Item> RUINS_GROUND = block(FalloutWastelandsModBlocks.RUINS_GROUND);
	public static final RegistryObject<Item> INDUSTRIAL_PLATING = block(FalloutWastelandsModBlocks.INDUSTRIAL_PLATING);
	public static final RegistryObject<Item> INDUSTRIAL_SUPPORT = block(FalloutWastelandsModBlocks.INDUSTRIAL_SUPPORT);
	public static final RegistryObject<Item> SINGLE_SCAFFOLD_BLOCK = block(FalloutWastelandsModBlocks.SINGLE_SCAFFOLD_BLOCK);
	public static final RegistryObject<Item> VAULT_WALL = block(FalloutWastelandsModBlocks.VAULT_WALL);
	public static final RegistryObject<Item> VAULT_REINFORCED_PILLAR = block(FalloutWastelandsModBlocks.VAULT_REINFORCED_PILLAR);
	public static final RegistryObject<Item> VAULT_WALL_CURVED = block(FalloutWastelandsModBlocks.VAULT_WALL_CURVED);
	public static final RegistryObject<Item> VAULT_WALL_EXPOSED = block(FalloutWastelandsModBlocks.VAULT_WALL_EXPOSED);
	public static final RegistryObject<Item> VAULT_FLOOR = block(FalloutWastelandsModBlocks.VAULT_FLOOR);
	public static final RegistryObject<Item> VAULT_PILLAR = block(FalloutWastelandsModBlocks.VAULT_PILLAR);
	public static final RegistryObject<Item> VAULT_VENT = block(FalloutWastelandsModBlocks.VAULT_VENT);
	public static final RegistryObject<Item> OXIDIZED_METAL_SLAB = block(FalloutWastelandsModBlocks.OXIDIZED_METAL_SLAB);
	public static final RegistryObject<Item> RUSTED_SHEET_METAL_WALL = block(FalloutWastelandsModBlocks.RUSTED_SHEET_METAL_WALL);
	public static final RegistryObject<Item> MILITARY_METAL_PLATE_WALL = block(FalloutWastelandsModBlocks.MILITARY_METAL_PLATE_WALL);
	public static final RegistryObject<Item> CHARRED_MOLDER_WOOD_PLANK = block(FalloutWastelandsModBlocks.CHARRED_MOLDER_WOOD_PLANK);
	public static final RegistryObject<Item> CHARRED_MOLDER_STAIRS = block(FalloutWastelandsModBlocks.CHARRED_MOLDER_STAIRS);
	public static final RegistryObject<Item> BOS_STEEL_SLABS = block(FalloutWastelandsModBlocks.BOS_STEEL_SLABS);
	public static final RegistryObject<Item> MILITARY_PLATING_SLAB = block(FalloutWastelandsModBlocks.MILITARY_PLATING_SLAB);
	public static final RegistryObject<Item> MILITARY_METAL_STAIR = block(FalloutWastelandsModBlocks.MILITARY_METAL_STAIR);
	public static final RegistryObject<Item> MILITARY_METAL_HAZARD = block(FalloutWastelandsModBlocks.MILITARY_METAL_HAZARD);
	public static final RegistryObject<Item> MILITARY_PLATING_WALKWAY = block(FalloutWastelandsModBlocks.MILITARY_PLATING_WALKWAY);
	public static final RegistryObject<Item> MILITARY_METAL_RADIATION = block(FalloutWastelandsModBlocks.MILITARY_METAL_RADIATION);
	public static final RegistryObject<Item> CHARRED_MOLDER_SLAB = block(FalloutWastelandsModBlocks.CHARRED_MOLDER_SLAB);
	public static final RegistryObject<Item> CHARRED_MOLDER_FENCE = block(FalloutWastelandsModBlocks.CHARRED_MOLDER_FENCE);
	public static final RegistryObject<Item> METAL_BARREL = block(FalloutWastelandsModBlocks.METAL_BARREL);
	public static final RegistryObject<Item> RADIATION_BARREL = block(FalloutWastelandsModBlocks.RADIATION_BARREL);
	public static final RegistryObject<Item> CEILING_LIGHT = block(FalloutWastelandsModBlocks.CEILING_LIGHT);
	public static final RegistryObject<Item> FILING_CABINET = block(FalloutWastelandsModBlocks.FILING_CABINET);
	public static final RegistryObject<Item> FLOOR_PAPERS = block(FalloutWastelandsModBlocks.FLOOR_PAPERS);
	public static final RegistryObject<Item> FRIDGE = block(FalloutWastelandsModBlocks.FRIDGE);
	public static final RegistryObject<Item> MEDICAL_BOX = block(FalloutWastelandsModBlocks.MEDICAL_BOX);
	public static final RegistryObject<Item> METAL_CHAIR = block(FalloutWastelandsModBlocks.METAL_CHAIR);
	public static final RegistryObject<Item> MIXER = block(FalloutWastelandsModBlocks.MIXER);
	public static final RegistryObject<Item> PIPE = block(FalloutWastelandsModBlocks.PIPE);
	public static final RegistryObject<Item> TELEVISION = block(FalloutWastelandsModBlocks.TELEVISION);
	public static final RegistryObject<Item> TERMINAL = block(FalloutWastelandsModBlocks.TERMINAL);
	public static final RegistryObject<Item> TIRE_STACK = block(FalloutWastelandsModBlocks.TIRE_STACK);
	public static final RegistryObject<Item> TRASH_BIN = block(FalloutWastelandsModBlocks.TRASH_BIN);
	public static final RegistryObject<Item> AMMO_BOX = block(FalloutWastelandsModBlocks.AMMO_BOX);
	public static final RegistryObject<Item> LIGHT_TUBE = block(FalloutWastelandsModBlocks.LIGHT_TUBE);
	public static final RegistryObject<Item> ENCLAVE_BUNKER_STAIRS = block(FalloutWastelandsModBlocks.ENCLAVE_BUNKER_STAIRS);
	public static final RegistryObject<Item> METAL_SHELF = block(FalloutWastelandsModBlocks.METAL_SHELF);
	public static final RegistryObject<Item> BOS_METAL_STAIRS = block(FalloutWastelandsModBlocks.BOS_METAL_STAIRS);
	public static final RegistryObject<Item> POWER_ARMOR_FRAME_SPAWN_EGG = REGISTRY.register("power_armor_frame_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.POWER_ARMOR_FRAME, -5000297, -2828339, new Item.Properties()));
	public static final RegistryObject<Item> POWER_ARMOR_FRAME_ARMOR_HELMET = REGISTRY.register("power_armor_frame_armor_helmet", () -> new PowerArmorFrameArmorItem.Helmet());
	public static final RegistryObject<Item> POWER_ARMOR_FRAME_ARMOR_CHESTPLATE = REGISTRY.register("power_armor_frame_armor_chestplate", () -> new PowerArmorFrameArmorItem.Chestplate());
	public static final RegistryObject<Item> POWER_ARMOR_FRAME_ARMOR_LEGGINGS = REGISTRY.register("power_armor_frame_armor_leggings", () -> new PowerArmorFrameArmorItem.Leggings());
	public static final RegistryObject<Item> POWER_ARMOR_FRAME_ARMOR_BOOTS = REGISTRY.register("power_armor_frame_armor_boots", () -> new PowerArmorFrameArmorItem.Boots());
	public static final RegistryObject<Item> T_45_PA_HELMET = REGISTRY.register("t_45_pa_helmet", () -> new T45PAItem.Helmet());
	public static final RegistryObject<Item> T_45_PA_CHESTPLATE = REGISTRY.register("t_45_pa_chestplate", () -> new T45PAItem.Chestplate());
	public static final RegistryObject<Item> T_45_PA_LEGGINGS = REGISTRY.register("t_45_pa_leggings", () -> new T45PAItem.Leggings());
	public static final RegistryObject<Item> T_45_PA_BOOTS = REGISTRY.register("t_45_pa_boots", () -> new T45PAItem.Boots());
	public static final RegistryObject<Item> ALUMINIUMNUGGET = REGISTRY.register("aluminiumnugget", () -> new AluminiumnuggetItem());
	public static final RegistryObject<Item> LEAD_NUGGET = REGISTRY.register("lead_nugget", () -> new LeadNuggetItem());
	public static final RegistryObject<Item> STEELNUGGET = REGISTRY.register("steelnugget", () -> new SteelnuggetItem());
	public static final RegistryObject<Item> TINNUGGET = REGISTRY.register("tinnugget", () -> new TinnuggetItem());
	public static final RegistryObject<Item> URANIUM_NUGGET = REGISTRY.register("uranium_nugget", () -> new UraniumNuggetItem());
	public static final RegistryObject<Item> BASE_GUN_ITEM = REGISTRY.register("base_gun_item", () -> new BaseGunItemItem());
	public static final RegistryObject<Item> RIPPER_PROJECTILE = REGISTRY.register("ripper_projectile", () -> new RipperProjectileItem());
	public static final RegistryObject<Item> PA_FRAME_ITEM = REGISTRY.register("pa_frame_item", () -> new PAFrameItemItem());
	public static final RegistryObject<Item> PA_DISPLAY_ENTITY_SPAWN_EGG = REGISTRY.register("pa_display_entity_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.PA_DISPLAY_ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> RAIDER_DUSTWALKER_SPAWN_EGG = REGISTRY.register("raider_dustwalker_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.RAIDER_DUSTWALKER, -8423335, -9939410, new Item.Properties()));
	public static final RegistryObject<Item> BLASTMASTER_RAIDER_SPAWN_EGG = REGISTRY.register("blastmaster_raider_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.BLASTMASTER_RAIDER, -8423335, -9939410, new Item.Properties()));
	public static final RegistryObject<Item> RAIDERSCAVANGER_SPAWN_EGG = REGISTRY.register("raiderscavanger_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.RAIDERSCAVANGER, -8423335, -9939410, new Item.Properties()));
	public static final RegistryObject<Item> WASTELANDDRYDIRT = block(FalloutWastelandsModBlocks.WASTELANDDRYDIRT);
	public static final RegistryObject<Item> ROCKYDIRT = block(FalloutWastelandsModBlocks.ROCKYDIRT);
	public static final RegistryObject<Item> BRAHMIN_MEAT = REGISTRY.register("brahmin_meat", () -> new BrahimMeatItem());
	public static final RegistryObject<Item> FERTILIZER = REGISTRY.register("fertilizer", () -> new FertilizerItem());
	public static final RegistryObject<Item> DENTED_CAN = REGISTRY.register("dented_can", () -> new DentedCanItem());
	public static final RegistryObject<Item> MUTLEMON = REGISTRY.register("mutlemon", () -> new MutlemonItem());
	public static final RegistryObject<Item> COFFEE = REGISTRY.register("coffee", () -> new CoffeeItem());
	public static final RegistryObject<Item> COFFEPOT = REGISTRY.register("coffepot", () -> new CoffepotItem());
	public static final RegistryObject<Item> CIGARETTEPACK = REGISTRY.register("cigarettepack", () -> new CigarettepackItem());
	public static final RegistryObject<Item> MOTHERBOARD = REGISTRY.register("motherboard", () -> new MotherboardItem());
	public static final RegistryObject<Item> INDUSTRIALHULL = REGISTRY.register("industrialhull", () -> new IndustrialhullItem());
	public static final RegistryObject<Item> BROTHERHOOD_HULL = REGISTRY.register("brotherhood_hull", () -> new BrotherhoodHullItem());
	public static final RegistryObject<Item> ENCLAVE_HULL = REGISTRY.register("enclave_hull", () -> new EnclaveHullItem());
	public static final RegistryObject<Item> FUSION_CORE = REGISTRY.register("fusion_core", () -> new FusionCoreItem());
	public static final RegistryObject<Item> SMALLCALIBERCASING = REGISTRY.register("smallcalibercasing", () -> new SmallcalibercasingItem());
	public static final RegistryObject<Item> HEAVYCALIBERCASING = REGISTRY.register("heavycalibercasing", () -> new HeavycalibercasingItem());
	public static final RegistryObject<Item> HUNTING_CASING = REGISTRY.register("hunting_casing", () -> new HuntingCasingItem());
	public static final RegistryObject<Item> CANNED_BEEF = REGISTRY.register("canned_beef", () -> new CannedBeefItem());
	public static final RegistryObject<Item> SUGAR_BOMBS = REGISTRY.register("sugar_bombs", () -> new SugarBombsItem());
	public static final RegistryObject<Item> INSTAMASH = REGISTRY.register("instamash", () -> new InstamashItem());
	public static final RegistryObject<Item> CRAM = REGISTRY.register("cram", () -> new CramItem());
	public static final RegistryObject<Item> IGUANA_ON_STICK = REGISTRY.register("iguana_on_stick", () -> new IguanaOnStickItem());
	public static final RegistryObject<Item> CHICAGO_OMELETTE = REGISTRY.register("chicago_omelette", () -> new ChicagoOmeletteItem());
	public static final RegistryObject<Item> GECKO_COOCKED_EGG = REGISTRY.register("gecko_coocked_egg", () -> new GeckoCoockedEggItem());
	public static final RegistryObject<Item> GECKO_EGG = REGISTRY.register("gecko_egg", () -> new GeckoEggItem());
	public static final RegistryObject<Item> HUMAN_BRAIN = REGISTRY.register("human_brain", () -> new HumanBrainItem());
	public static final RegistryObject<Item> BLOAT_FLY_MEAT = REGISTRY.register("bloat_fly_meat", () -> new BloatFlyMeatItem());
	public static final RegistryObject<Item> MUG = REGISTRY.register("mug", () -> new MugItem());
	public static final RegistryObject<Item> ADVANCED_MOTHERBOARD = REGISTRY.register("advanced_motherboard", () -> new AdvancedMotherboardItem());
	public static final RegistryObject<Item> ACID = REGISTRY.register("acid", () -> new AcidItem());
	public static final RegistryObject<Item> GREY_INDUSTRIAL_ALLOY = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_ALLOY);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_ALLOYPLATE = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_ALLOYPLATE);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_ALLOWMIDRIVET = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_ALLOWMIDRIVET);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_ALLOYBOTTOMRIVET = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_ALLOYBOTTOMRIVET);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_WALKWAY = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_WALKWAY);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_WALKWAYSLAB = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_WALKWAYSLAB);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_WALKWAY_STAIRS = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_WALKWAY_STAIRS);
	public static final RegistryObject<Item> INDUSTRIAL_WALKWAYSTAIRS = block(FalloutWastelandsModBlocks.INDUSTRIAL_WALKWAYSTAIRS);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_WALKWAY_SLAB = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_WALKWAY_SLAB);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_ALLOY_STAIR = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_ALLOY_STAIR);
	public static final RegistryObject<Item> GREY_INDUSTRIAL_ALLOY_SLAB = block(FalloutWastelandsModBlocks.GREY_INDUSTRIAL_ALLOY_SLAB);
	public static final RegistryObject<Item> WASTELAND_BRICKS_SLAB = block(FalloutWastelandsModBlocks.WASTELAND_BRICKS_SLAB);
	public static final RegistryObject<Item> WASTELAND_BRICKS_STAIRS = block(FalloutWastelandsModBlocks.WASTELAND_BRICKS_STAIRS);
	public static final RegistryObject<Item> WORN_METAL_PILLAR = block(FalloutWastelandsModBlocks.WORN_METAL_PILLAR);
	public static final RegistryObject<Item> RADIACTIVE_WASTE = REGISTRY.register("radiactive_waste", () -> new RadiactiveWasteItem());
	public static final RegistryObject<Item> MOTOR = REGISTRY.register("motor", () -> new MotorItem());
	public static final RegistryObject<Item> METALSTICK = REGISTRY.register("metalstick", () -> new MetalstickItem());
	public static final RegistryObject<Item> MILITARY_HULL = REGISTRY.register("military_hull", () -> new MilitaryHullItem());
	public static final RegistryObject<Item> PLASTICSHEET = REGISTRY.register("plasticsheet", () -> new PlasticsheetItem());
	public static final RegistryObject<Item> ADVANCED_MOTOR = REGISTRY.register("advanced_motor", () -> new AdvancedMotorItem());
	public static final RegistryObject<Item> BEER = REGISTRY.register("beer", () -> new BeerItem());
	public static final RegistryObject<Item> BO_S_METAL_PLATING_SLAB = block(FalloutWastelandsModBlocks.BO_S_METAL_PLATING_SLAB);
	public static final RegistryObject<Item> MILITARYPLATINGSTAIRS = block(FalloutWastelandsModBlocks.MILITARYPLATINGSTAIRS);
	public static final RegistryObject<Item> MILITARY_PLATING_WALKWAY_SLAB = block(FalloutWastelandsModBlocks.MILITARY_PLATING_WALKWAY_SLAB);
	public static final RegistryObject<Item> ABRAXO_CLEANER = REGISTRY.register("abraxo_cleaner", () -> new AbraxoCleanerItem());
	public static final RegistryObject<Item> STEEL_COMPOSITE = REGISTRY.register("steel_composite", () -> new SteelCompositeItem());
	public static final RegistryObject<Item> WORN_METAL_DECORATION = block(FalloutWastelandsModBlocks.WORN_METAL_DECORATION);
	public static final RegistryObject<Item> WORN_METAL_DECORATIONSTAIRS = block(FalloutWastelandsModBlocks.WORN_METAL_DECORATIONSTAIRS);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOYSTRUCTURE = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOYSTRUCTURE);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY_STRUCTURESLAB = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY_STRUCTURESLAB);
	public static final RegistryObject<Item> INDUSTRIAL_ALLOY_VENT = block(FalloutWastelandsModBlocks.INDUSTRIAL_ALLOY_VENT);
	public static final RegistryObject<Item> RED_PAINTED_PLANKS = block(FalloutWastelandsModBlocks.RED_PAINTED_PLANKS);
	public static final RegistryObject<Item> YUKAPLANT = doubleBlock(FalloutWastelandsModBlocks.YUKAPLANT);
	public static final RegistryObject<Item> MIRELURKMEAT = REGISTRY.register("mirelurkmeat", () -> new MirelurkmeatItem());
	public static final RegistryObject<Item> WASTELAND_ROAD_YELLOW = block(FalloutWastelandsModBlocks.WASTELAND_ROAD_YELLOW);
	public static final RegistryObject<Item> TATOPLANT_0 = doubleBlock(FalloutWastelandsModBlocks.TATOPLANT_0);
	public static final RegistryObject<Item> TATOPLANT_2 = doubleBlock(FalloutWastelandsModBlocks.TATOPLANT_2);
	public static final RegistryObject<Item> TATOPLANT_1 = doubleBlock(FalloutWastelandsModBlocks.TATOPLANT_1);
	public static final RegistryObject<Item> WASTELAND_ROAD_YELLOW_SLAB = block(FalloutWastelandsModBlocks.WASTELAND_ROAD_YELLOW_SLAB);
	public static final RegistryObject<Item> BRAHMIN_SPAWN_EGG = REGISTRY.register("brahmin_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.BRAHMIN, -10205395, -7046050, new Item.Properties()));
	public static final RegistryObject<Item> TATOPLANT_4 = doubleBlock(FalloutWastelandsModBlocks.TATOPLANT_4);
	public static final RegistryObject<Item> TATOPLANT_3 = doubleBlock(FalloutWastelandsModBlocks.TATOPLANT_3);
	public static final RegistryObject<Item> WASTELAND_ROAD_WHITE = block(FalloutWastelandsModBlocks.WASTELAND_ROAD_WHITE);
	public static final RegistryObject<Item> WASTELAND_ROAD_WHITE_SLAB = block(FalloutWastelandsModBlocks.WASTELAND_ROAD_WHITE_SLAB);
	public static final RegistryObject<Item> NOODLES = REGISTRY.register("noodles", () -> new NoodlesItem());
	public static final RegistryObject<Item> ROAD_LEATHER_HELMET = REGISTRY.register("road_leather_helmet", () -> new RoadLeatherItem.Helmet());
	public static final RegistryObject<Item> ROAD_LEATHER_CHESTPLATE = REGISTRY.register("road_leather_chestplate", () -> new RoadLeatherItem.Chestplate());
	public static final RegistryObject<Item> ROAD_LEATHER_LEGGINGS = REGISTRY.register("road_leather_leggings", () -> new RoadLeatherItem.Leggings());
	public static final RegistryObject<Item> ROAD_LEATHER_BOOTS = REGISTRY.register("road_leather_boots", () -> new RoadLeatherItem.Boots());
	public static final RegistryObject<Item> T_51B_PA_HELMET = REGISTRY.register("t_51b_pa_helmet", () -> new T51bPAItem.Helmet());
	public static final RegistryObject<Item> T_51B_PA_CHESTPLATE = REGISTRY.register("t_51b_pa_chestplate", () -> new T51bPAItem.Chestplate());
	public static final RegistryObject<Item> T_51B_PA_LEGGINGS = REGISTRY.register("t_51b_pa_leggings", () -> new T51bPAItem.Leggings());
	public static final RegistryObject<Item> T_51B_PA_BOOTS = REGISTRY.register("t_51b_pa_boots", () -> new T51bPAItem.Boots());
	public static final RegistryObject<Item> BOS_DOOR_2 = doubleBlock(FalloutWastelandsModBlocks.BOS_DOOR_2);
	public static final RegistryObject<Item> VAULT_HULL = REGISTRY.register("vault_hull", () -> new VaultHullItem());
	public static final RegistryObject<Item> BO_S_GRID_FLOOR = block(FalloutWastelandsModBlocks.BO_S_GRID_FLOOR);
	public static final RegistryObject<Item> BO_S_GRID_FLOOR_STAIRS = block(FalloutWastelandsModBlocks.BO_S_GRID_FLOOR_STAIRS);
	public static final RegistryObject<Item> BO_S_GRID_FLOOR_SLAB = block(FalloutWastelandsModBlocks.BO_S_GRID_FLOOR_SLAB);
	public static final RegistryObject<Item> BO_S_METAL_ROOF = block(FalloutWastelandsModBlocks.BO_S_METAL_ROOF);
	public static final RegistryObject<Item> BOS_METAL_ROOF_STAIRS = block(FalloutWastelandsModBlocks.BOS_METAL_ROOF_STAIRS);
	public static final RegistryObject<Item> BO_S_STEEL_WALL = block(FalloutWastelandsModBlocks.BO_S_STEEL_WALL);
	public static final RegistryObject<Item> BO_S_TILE = block(FalloutWastelandsModBlocks.BO_S_TILE);
	public static final RegistryObject<Item> BOS_METAL_PLATINGCONNECTED = block(FalloutWastelandsModBlocks.BOS_METAL_PLATINGCONNECTED);
	public static final RegistryObject<Item> VACCUM_TUBE = REGISTRY.register("vaccum_tube", () -> new VaccumTubeItem());
	public static final RegistryObject<Item> MACHETE = REGISTRY.register("machete", () -> new MacheteItem());
	public static final RegistryObject<Item> CATTLE_ROD = REGISTRY.register("cattle_rod", () -> new CattleRodItem());
	public static final RegistryObject<Item> BASEBALL_BAT = REGISTRY.register("baseball_bat", () -> new BaseballBatItem());
	public static final RegistryObject<Item> BO_S_DATA_FRONT_BOTTOM = block(FalloutWastelandsModBlocks.BO_S_DATA_FRONT_BOTTOM);
	public static final RegistryObject<Item> BO_S_DATA_FRONT_MIDDLE = block(FalloutWastelandsModBlocks.BO_S_DATA_FRONT_MIDDLE);
	public static final RegistryObject<Item> BO_S_DATA_FRONT_TOP = block(FalloutWastelandsModBlocks.BO_S_DATA_FRONT_TOP);
	public static final RegistryObject<Item> BASEBALL_CLUB = REGISTRY.register("baseball_club", () -> new BaseballClubItem());
	public static final RegistryObject<Item> WINE = REGISTRY.register("wine", () -> new WineItem());
	public static final RegistryObject<Item> GAMMA_GULP_BEER = REGISTRY.register("gamma_gulp_beer", () -> new GammaGulpBeerItem());
	public static final RegistryObject<Item> SCOTCH = REGISTRY.register("scotch", () -> new ScotchItem());
	public static final RegistryObject<Item> WHISKEY = REGISTRY.register("whiskey", () -> new WhiskeyItem());
	public static final RegistryObject<Item> ROENTGEN_RUM = REGISTRY.register("roentgen_rum", () -> new RoentgenRumItem());
	public static final RegistryObject<Item> ABSINTHE = REGISTRY.register("absinthe", () -> new AbsintheItem());
	public static final RegistryObject<Item> VODKA = REGISTRY.register("vodka", () -> new VodkaItem());
	public static final RegistryObject<Item> ENCLAVEOFFICIER_SUIT_HELMET = REGISTRY.register("enclaveofficier_suit_helmet", () -> new EnclaveofficierSuitItem.Helmet());
	public static final RegistryObject<Item> ENCLAVEOFFICIER_SUIT_CHESTPLATE = REGISTRY.register("enclaveofficier_suit_chestplate", () -> new EnclaveofficierSuitItem.Chestplate());
	public static final RegistryObject<Item> ENCLAVEOFFICIER_SUIT_LEGGINGS = REGISTRY.register("enclaveofficier_suit_leggings", () -> new EnclaveofficierSuitItem.Leggings());
	public static final RegistryObject<Item> ENCLAVEOFFICIER_SUIT_BOOTS = REGISTRY.register("enclaveofficier_suit_boots", () -> new EnclaveofficierSuitItem.Boots());
	public static final RegistryObject<Item> ADOBE_BLOCK = block(FalloutWastelandsModBlocks.ADOBE_BLOCK);
	public static final RegistryObject<Item> ADOBE_STAIRS = block(FalloutWastelandsModBlocks.ADOBE_STAIRS);
	public static final RegistryObject<Item> ADOBE_BLOCK_SLAB = block(FalloutWastelandsModBlocks.ADOBE_BLOCK_SLAB);
	public static final RegistryObject<Item> ADOBE_BLOCK_WALL = block(FalloutWastelandsModBlocks.ADOBE_BLOCK_WALL);
	public static final RegistryObject<Item> WASTELAND_SAND_STONE = block(FalloutWastelandsModBlocks.WASTELAND_SAND_STONE);
	public static final RegistryObject<Item> RAIDER_WARMONGER_HELMET = REGISTRY.register("raider_warmonger_helmet", () -> new RaiderWarmongerItem.Helmet());
	public static final RegistryObject<Item> RAIDER_WARMONGER_CHESTPLATE = REGISTRY.register("raider_warmonger_chestplate", () -> new RaiderWarmongerItem.Chestplate());
	public static final RegistryObject<Item> RAIDER_WARMONGER_LEGGINGS = REGISTRY.register("raider_warmonger_leggings", () -> new RaiderWarmongerItem.Leggings());
	public static final RegistryObject<Item> RAIDER_WARMONGER_BOOTS = REGISTRY.register("raider_warmonger_boots", () -> new RaiderWarmongerItem.Boots());
	public static final RegistryObject<Item> VARMINT_RIFLE = REGISTRY.register("varmint_rifle", () -> new VarmintRifleItem());
	public static final RegistryObject<Item> DEATHCLAW_GAUNTLET = REGISTRY.register("deathclaw_gauntlet", () -> new DeathclawGauntletItem());
	public static final RegistryObject<Item> LIGHTBULB = block(FalloutWastelandsModBlocks.LIGHTBULB);
	public static final RegistryObject<Item> LIGHTBULBON = block(FalloutWastelandsModBlocks.LIGHTBULBON);
	public static final RegistryObject<Item> DEATHCLAWHAND = REGISTRY.register("deathclawhand", () -> new DeathclawhandItem());
	public static final RegistryObject<Item> WONDERGLUE = REGISTRY.register("wonderglue", () -> new WonderglueItem());
	public static final RegistryObject<Item> FISSION_BATTERY = REGISTRY.register("fission_battery", () -> new FissionBatteryItem());
	public static final RegistryObject<Item> LOBOTOMITE_SUIT_HELMET = REGISTRY.register("lobotomite_suit_helmet", () -> new LobotomiteSuitItem.Helmet());
	public static final RegistryObject<Item> LOBOTOMITE_SUIT_CHESTPLATE = REGISTRY.register("lobotomite_suit_chestplate", () -> new LobotomiteSuitItem.Chestplate());
	public static final RegistryObject<Item> LOBOTOMITE_SUIT_LEGGINGS = REGISTRY.register("lobotomite_suit_leggings", () -> new LobotomiteSuitItem.Leggings());
	public static final RegistryObject<Item> LOBOTOMITE_SUIT_BOOTS = REGISTRY.register("lobotomite_suit_boots", () -> new LobotomiteSuitItem.Boots());
	public static final RegistryObject<Item> ROBCO_REPAIRMAN_CHESTPLATE = REGISTRY.register("robco_repairman_chestplate", () -> new RobcoRepairmanItem.Chestplate());
	public static final RegistryObject<Item> ROBCO_REPAIRMAN_LEGGINGS = REGISTRY.register("robco_repairman_leggings", () -> new RobcoRepairmanItem.Leggings());
	public static final RegistryObject<Item> ROBCO_REPAIRMAN_BOOTS = REGISTRY.register("robco_repairman_boots", () -> new RobcoRepairmanItem.Boots());
	public static final RegistryObject<Item> GECKO_SPAWN_EGG = REGISTRY.register("gecko_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.GECKO, -14988467, -9728619, new Item.Properties()));
	public static final RegistryObject<Item> HANDYMAN_SUIT_HELMET = REGISTRY.register("handyman_suit_helmet", () -> new HandymanSuitItem.Helmet());
	public static final RegistryObject<Item> HANDYMAN_SUIT_CHESTPLATE = REGISTRY.register("handyman_suit_chestplate", () -> new HandymanSuitItem.Chestplate());
	public static final RegistryObject<Item> HANDYMAN_SUIT_LEGGINGS = REGISTRY.register("handyman_suit_leggings", () -> new HandymanSuitItem.Leggings());
	public static final RegistryObject<Item> HANDYMAN_SUIT_BOOTS = REGISTRY.register("handyman_suit_boots", () -> new HandymanSuitItem.Boots());
	public static final RegistryObject<Item> ARMY_REPAIRMAN_SUIT_CHESTPLATE = REGISTRY.register("army_repairman_suit_chestplate", () -> new ArmyRepairmanSuitItem.Chestplate());
	public static final RegistryObject<Item> ARMY_REPAIRMAN_SUIT_LEGGINGS = REGISTRY.register("army_repairman_suit_leggings", () -> new ArmyRepairmanSuitItem.Leggings());
	public static final RegistryObject<Item> ARMY_REPAIRMAN_SUIT_BOOTS = REGISTRY.register("army_repairman_suit_boots", () -> new ArmyRepairmanSuitItem.Boots());
	public static final RegistryObject<Item> LOBOTOMITE_WALKER_SPAWN_EGG = REGISTRY.register("lobotomite_walker_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.LOBOTOMITE_WALKER, -11382217, -9939410, new Item.Properties()));
	public static final RegistryObject<Item> ENCLAVE_ANTIRADSUIT_HELMET = REGISTRY.register("enclave_antiradsuit_helmet", () -> new EnclaveAntiradsuitItem.Helmet());
	public static final RegistryObject<Item> ENCLAVE_ANTIRADSUIT_CHESTPLATE = REGISTRY.register("enclave_antiradsuit_chestplate", () -> new EnclaveAntiradsuitItem.Chestplate());
	public static final RegistryObject<Item> ENCLAVE_ANTIRADSUIT_LEGGINGS = REGISTRY.register("enclave_antiradsuit_leggings", () -> new EnclaveAntiradsuitItem.Leggings());
	public static final RegistryObject<Item> ENCLAVE_ANTIRADSUIT_BOOTS = REGISTRY.register("enclave_antiradsuit_boots", () -> new EnclaveAntiradsuitItem.Boots());
	public static final RegistryObject<Item> VAULT_SUIT_CHESTPLATE = REGISTRY.register("vault_suit_chestplate", () -> new VaultSuitItem.Chestplate());
	public static final RegistryObject<Item> VAULT_SUIT_LEGGINGS = REGISTRY.register("vault_suit_leggings", () -> new VaultSuitItem.Leggings());
	public static final RegistryObject<Item> VAULT_SUIT_BOOTS = REGISTRY.register("vault_suit_boots", () -> new VaultSuitItem.Boots());
	public static final RegistryObject<Item> SECURITY_BATON = REGISTRY.register("security_baton", () -> new SecurityBatonItem());
	public static final RegistryObject<Item> SUPER_SLEDGE = REGISTRY.register("super_sledge", () -> new SuperSledgeItem());
	public static final RegistryObject<Item> POTATO_CRISPS = REGISTRY.register("potato_crisps", () -> new PotatoCrispsItem());
	public static final RegistryObject<Item> JOSHUA_LOG = block(FalloutWastelandsModBlocks.JOSHUA_LOG);
	public static final RegistryObject<Item> JOSHUA_TREE_WOODPLANKS = block(FalloutWastelandsModBlocks.JOSHUA_TREE_WOODPLANKS);
	public static final RegistryObject<Item> JOSHUEA_TREE_STAIRS = block(FalloutWastelandsModBlocks.JOSHUEA_TREE_STAIRS);
	public static final RegistryObject<Item> JOSHUA_TREE_SLAB = block(FalloutWastelandsModBlocks.JOSHUA_TREE_SLAB);
	public static final RegistryObject<Item> JOSHUA_TREE_DOOR = doubleBlock(FalloutWastelandsModBlocks.JOSHUA_TREE_DOOR);
	public static final RegistryObject<Item> JOSHUA_TREE_DOORTRAP = block(FalloutWastelandsModBlocks.JOSHUA_TREE_DOORTRAP);
	public static final RegistryObject<Item> STOPROADSIGN = block(FalloutWastelandsModBlocks.STOPROADSIGN);
	public static final RegistryObject<Item> YIELROADSIGN = block(FalloutWastelandsModBlocks.YIELROADSIGN);
	public static final RegistryObject<Item> SANDBAGS = block(FalloutWastelandsModBlocks.SANDBAGS);
	public static final RegistryObject<Item> SANDBAGSTAIRS = block(FalloutWastelandsModBlocks.SANDBAGSTAIRS);
	public static final RegistryObject<Item> SANDBAGS_SLAB = block(FalloutWastelandsModBlocks.SANDBAGS_SLAB);
	public static final RegistryObject<Item> VAULT_SECURITY_SUIT_HELMET = REGISTRY.register("vault_security_suit_helmet", () -> new VaultSecuritySuitItem.Helmet());
	public static final RegistryObject<Item> VAULT_SECURITY_SUIT_CHESTPLATE = REGISTRY.register("vault_security_suit_chestplate", () -> new VaultSecuritySuitItem.Chestplate());
	public static final RegistryObject<Item> VAULT_SECURITY_SUIT_LEGGINGS = REGISTRY.register("vault_security_suit_leggings", () -> new VaultSecuritySuitItem.Leggings());
	public static final RegistryObject<Item> VAULT_SECURITY_SUIT_BOOTS = REGISTRY.register("vault_security_suit_boots", () -> new VaultSecuritySuitItem.Boots());
	public static final RegistryObject<Item> METAL_BOX = block(FalloutWastelandsModBlocks.METAL_BOX);
	public static final RegistryObject<Item> DYNAMITE_ENTITY_SPAWN_EGG = REGISTRY.register("dynamite_entity_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.DYNAMITE_ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DYNAMITE_ITEM = REGISTRY.register("dynamite_item", () -> new DynamiteItemItem());
	public static final RegistryObject<Item> KNIFE = REGISTRY.register("knife", () -> new KnifeItem());
	public static final RegistryObject<Item> JOSHUA_LOG_LOG = block(FalloutWastelandsModBlocks.JOSHUA_LOG_LOG);
	public static final RegistryObject<Item> STRIPPEDMOLDERWOODWOOD = block(FalloutWastelandsModBlocks.STRIPPEDMOLDERWOODWOOD);
	public static final RegistryObject<Item> OVEN = block(FalloutWastelandsModBlocks.OVEN);
	public static final RegistryObject<Item> CANNIBAL_01_SPAWN_EGG = REGISTRY.register("cannibal_01_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.CANNIBAL_01, -13552077, -9606326, new Item.Properties()));
	public static final RegistryObject<Item> JOSHUA_LEAVES = block(FalloutWastelandsModBlocks.JOSHUA_LEAVES);
	public static final RegistryObject<Item> ROOF_METAL_WALL = block(FalloutWastelandsModBlocks.ROOF_METAL_WALL);
	public static final RegistryObject<Item> ROOF_METAL_SLAB = block(FalloutWastelandsModBlocks.ROOF_METAL_SLAB);
	public static final RegistryObject<Item> DRIED_PLANKS = block(FalloutWastelandsModBlocks.DRIED_PLANKS);
	public static final RegistryObject<Item> DRIED_PLANKS_WALL = block(FalloutWastelandsModBlocks.DRIED_PLANKS_WALL);
	public static final RegistryObject<Item> SPIDERFLOATER_SPAWN_EGG = REGISTRY.register("spiderfloater_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.SPIDERFLOATER, -11127510, -5934277, new Item.Properties()));
	public static final RegistryObject<Item> WASTELAND_DRIED_GRASS = block(FalloutWastelandsModBlocks.WASTELAND_DRIED_GRASS);
	public static final RegistryObject<Item> CANNIBAL_02_SPAWN_EGG = REGISTRY.register("cannibal_02_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.CANNIBAL_02, -12500183, -7440039, new Item.Properties()));
	public static final RegistryObject<Item> VAULT_TILE_1 = block(FalloutWastelandsModBlocks.VAULT_TILE_1);
	public static final RegistryObject<Item> VAULT_TILE_2 = block(FalloutWastelandsModBlocks.VAULT_TILE_2);
	public static final RegistryObject<Item> VAULT_TILE_3 = block(FalloutWastelandsModBlocks.VAULT_TILE_3);
	public static final RegistryObject<Item> VAULT_TILE_4 = block(FalloutWastelandsModBlocks.VAULT_TILE_4);
	public static final RegistryObject<Item> VAULT_TILE_5 = block(FalloutWastelandsModBlocks.VAULT_TILE_5);
	public static final RegistryObject<Item> FLOATER_SPAWN_EGG = REGISTRY.register("floater_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.FLOATER, -11127510, -5934277, new Item.Properties()));
	public static final RegistryObject<Item> CURTAIN = block(FalloutWastelandsModBlocks.CURTAIN);
	public static final RegistryObject<Item> VAULT_WALL_YELLO = block(FalloutWastelandsModBlocks.VAULT_WALL_YELLO);
	public static final RegistryObject<Item> INDUS_PIPE_HUB = block(FalloutWastelandsModBlocks.INDUS_PIPE_HUB);
	public static final RegistryObject<Item> INDUS_PIPE = block(FalloutWastelandsModBlocks.INDUS_PIPE);
	public static final RegistryObject<Item> ENCASED_INDUS_PIPE = block(FalloutWastelandsModBlocks.ENCASED_INDUS_PIPE);
	public static final RegistryObject<Item> RADROACH_SPAWN_EGG = REGISTRY.register("radroach_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.RADROACH, -14410475, -13751529, new Item.Properties()));
	public static final RegistryObject<Item> VAULT_DOOR_SEALED = block(FalloutWastelandsModBlocks.VAULT_DOOR_SEALED);
	public static final RegistryObject<Item> VAULT_DOOR_OPEN = block(FalloutWastelandsModBlocks.VAULT_DOOR_OPEN);
	public static final RegistryObject<Item> RADROACH_MEAT = REGISTRY.register("radroach_meat", () -> new RadroachMeatItem());
	public static final RegistryObject<Item> RAD_ISLAND_CIDER = REGISTRY.register("rad_island_cider", () -> new RadIslandCiderItem());
	public static final RegistryObject<Item> SIERRA_MADRE_MARTINI = REGISTRY.register("sierra_madre_martini", () -> new SierraMadreMartiniItem());
	public static final RegistryObject<Item> STRANGE_MEAT_PATTY = REGISTRY.register("strange_meat_patty", () -> new StrangeMeatPattyItem());
	public static final RegistryObject<Item> MIRELURK_CAKE = REGISTRY.register("mirelurk_cake", () -> new MirelurkCakeItem());
	public static final RegistryObject<Item> RADSCORPION_SPAWN_EGG = REGISTRY.register("radscorpion_spawn_egg", () -> new ForgeSpawnEggItem(FalloutWastelandsModEntities.RADSCORPION, -5146569, -11256031, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
